<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> '',
	'DIRECTION'			=> 'ltr',
	'DATE_FORMAT'		=> '|Y M d |',	// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|Y M d , H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'			=> 'ko',

	// You can define different rules for the determination of plural forms here.
	// See https://area51.phpbb.com/docs/dev/3.3.x/language/plurals.html for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> '1 일',
	'1_MONTH'		=> '1 개월',
	'1_YEAR'		=> '1 년',
	'2_WEEKS'		=> '2 주',
	'3_MONTHS'		=> '3 개월',
	'6_MONTHS'		=> '6 개월',
	'7_DAYS'		=> '7 일',

	'ACCOUNT_ALREADY_ACTIVATED'		=> '귀하의 계정은 이미 활성화되었습니다.',
	'ACCOUNT_DEACTIVATED'			=> '우리 계정은 수동으로 비활성화되었으며 관리자만 다시 활성화할 수 있습니다.',
	'ACP'							=> '관리 제어판',
	'ACP_SHORT'						=> 'ACP',
	'ACTIVE'						=> '실행',
	'ACTIVE_ERROR'					=> '지정된 사용자 이름은 현재 비활성화되어 있습니다. 계정 활성화에 문제가 있는 경우 게시판 관리자에게 문의하세요',
	'ADMINISTRATOR'					=> '관리자',
	'ADMINISTRATORS'				=> '관리자',
	'AGE'							=> '나이',
	'AIM'							=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX 애러',
	'AJAX_ERROR_TEXT'				=> '요청을 처리하는 동안 문제가 발생했습니다.',
	'AJAX_ERROR_TEXT_ABORT'			=> '사용자가 요청을 중단했습니다.',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> '요청 시간이 초과되었습니다. 다시 시도해 주세요.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> '요청에 문제가 발생하여 서버에서 잘못된 응답을 반환했습니다.',
	'ALLOWED'						=> '허용된',
	'ALL_FILES'						=> '모든 파일',
	'ALL_FORUMS'					=> '모든 포럼',
	'ALL_MESSAGES'					=> '모든 메시지',
	'ALL_POSTS'						=> '모든 게시물',
	'ALL_TIMES'						=> '모든 시간표시는 <span title="%2$s">%1$s</span> 입니다',
	'ALL_TOPICS'					=> '모든 글',
	'ALT_TEXT'						=> '대체 텍스트',
	'AND'							=> '그리고',
	'ARE_WATCHING_FORUM'			=> '이 포럼의 새 게시물에 대한 알림을 받도록 구독했습니다.',
	'ARE_WATCHING_TOPIC'			=> '이 글을 새 게시물에 대한 알림을 받도록 구독했습니다.',
	'ASCENDING'						=> '오름차순',
	'ATTACHMENTS'					=> '첨부파일',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> '첨부하려는 이미지 파일이 잘못되었습니다.',
	'AUTHOR'						=> '작가',
	'AUTH_NO_PROFILE_CREATED'		=> '사용자 프로필 생성에 실패했습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_ALREADY_LINKED'				=> '이 외부 서비스는 이미 다른 보드 계정과 연결되어 있습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> '잘못된 데이터베이스 항목입니다',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'OAuth 서비스 핸들러에 잘못된 서비스 유형이 제공되었습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_REQUEST'						=> 'OAuth 요청을 처리하는 동안 문제가 발생했습니다.',
	'AUTH_PROVIDER_OAUTH_RETURN_ERROR'						=> '외부 서비스에서 잘못된 값을 반환했으므로 요청을 처리할 수 없습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'OAuth 서비스가 생성되지 않았습니다.',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> '비트리',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> '페이스북',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> '구글',
	'AUTH_PROVIDER_OAUTH_SERVICE_TWITTER'					=> '트위트',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'OAuth 토큰이 저장되지 않았습니다.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'OAuth 토큰이 잘못 저장되었습니다.',
	'AVATAR_DISALLOWED_CONTENT'		=> '업로드된 파일이 가능한 공격 벡터로 식별되었기 때문에 업로드가 거부되었습니다.',
	'AVATAR_DISALLOWED_EXTENSION'	=> '확장자 <strong>%s</strong>이(가) 허용되지 않으므로 이 파일을 표시할 수 없습니다.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> '원격 데이터가 잘못되었거나 손상된 것 같아서 지정된 아바타를 업로드할 수 없습니다.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> '업로드한 아바타 파일이 비어 있습니다.',
	'AVATAR_INVALID_FILENAME'		=> '%s은(는) 잘못된 파일 이름입니다.',
	'AVATAR_NOT_UPLOADED'			=> '아바타를 업로드할 수 없습니다.',
	'AVATAR_NO_TEMP_DIR'			=> '임시 폴더를 찾을 수 없거나 쓸 수 없습니다.',
	'AVATAR_NO_SIZE'				=> '연결된 아바타의 너비 또는 높이를 확인할 수 없습니다. 수동으로 입력하십시오.',
	'AVATAR_NO_UPLOAD_DIR'			=> '아바타 저장 경로가 존재하지 않거나 쓸 수 없습니다.',
	'AVATAR_NO_UPLOAD_PATH'			=> '아바타 업로드가 활성화되어 있지만 아바타 저장 경로가 설정되어 있지 않습니다',
	'AVATAR_PARTIAL_UPLOAD'			=> '지정된 파일이 부분적으로만 업로드되었습니다.',
	'AVATAR_PHP_SIZE_NA'			=> '아바타의 파일 크기가 너무 큽니다.<br />php.ini에 설정된 최대 허용 파일 크기를 결정할 수 없습니다.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> '아바타의 파일 크기가 너무 큽니다. 허용되는 최대 업로드 크기는 %1$d %2$s입니다.<br />이것은 php.ini에 설정되어 있으며 무시할 수 없습니다.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> '요청 시간이 초과되어 지정된 아바타를 업로드할 수 없습니다.',
	'AVATAR_PHP_UPLOAD_STOPPED'		=> 'PHP 확장 프로그램이 파일 업로드를 중지했습니다.',
	'AVATAR_URL_INVALID'			=> '지정한 URL이 잘못되었습니다.',
	'AVATAR_URL_NOT_FOUND'			=> '지정한 파일을 찾을 수 없습니다.',
	'AVATAR_WRONG_FILESIZE'			=> '아바타의 파일 크기는 0에서 %1$d %2$s 사이여야 합니다.',
	'AVATAR_WRONG_SIZE'				=> '제출된 아바타의 너비는 %5$s이고 높이는 %6$s입니다. 아바타는 너비가 %1$s 이상, 높이가 %2$s 이상이어야 하며 너비가 %3$s, 높이가 %4$s 이상이어야 합니다.',

	'BACK_TO_TOP'			=> '상위',
	'BACK_TO_PREV'			=> '이전 페이지로 돌아가기',
	'BAN_TRIGGERED_BY_EMAIL'=> '귀하의 이메일 주소가 차단되었습니다.',
	'BAN_TRIGGERED_BY_IP'	=> '당신의 IP 주소가 차단되었습니다.',
	'BAN_TRIGGERED_BY_USER'	=> '당신의 사용자 이름에 대한 금지 조치가 내려졌습니다.',
	'BBCODE_GUIDE'			=> 'BBCode 가이드',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> '생일자',
	'BOARD_BAN_PERM'		=> '이 게시판에서 <strong>영구적으로</strong> 차단되었습니다.<br /><br />자세한 내용은 %2$s게시판 관리자%3$s에게 문의하세요.',
	'BOARD_BAN_REASON'		=> '차단 사유: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> '<strong>%1$s</strong>까지 이 게시판에서 차단되었습니다.<br /><br />자세한 내용은 %2$s게시판 관리자%3$s에게 문의하세요.',
	'BOARD_DISABLE'			=> '죄송합니다. 이 게시판은 현재 사용할 수 없습니다.',
	'BOARD_DISABLED'		=> '이 보드는 현재 비활성화되어 있습니다.',
	'BOARD_UNAVAILABLE'		=> '죄송합니다. 보드를 일시적으로 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.',
	'BROWSING_FORUM'		=> '이 포럼을 사용중인 사용자: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> '이 포럼을 탐색하는 사용자: %2$s 및 손님 %1$d명',
		2	=> '이 포럼을 탐색하는 사용자: %2$s 및 손님 %1$d명',
	),
	'BUTTON_DELETE'         => '삭제',
	'BUTTON_EDIT'			=> '수정',
	'BUTTON_FORUM_LOCKED'	=> '잠김',
	'BUTTON_INFORMATION'    => '정보',
	'BUTTON_NEW_TOPIC'		=> '새글쓰기',
	'BUTTON_PM'				=> 'PM',
	'BUTTON_PM_FORWARD'		=> '앞으로',
	'BUTTON_PM_NEW'			=> '새로운 PM',
	'BUTTON_PM_REPLY'		=> '답장 보내기',
	'BUTTON_PM_REPLY_ALL'	=> '전체 답장',
	'BUTTON_POST_REPLY'		=> '답글 게시',
	'BUTTON_QUOTE'			=> '인용문',
	'BUTTON_REPORT'         => '보고서',
	'BUTTON_TOPIC_LOCKED'	=> '잠김',
	'BUTTON_WARN'           => '경고하다',
	'BYTES'					=> 'Bytes',
	'BYTES_SHORT'			=> 'B',

	'CANCEL'				=> '취소',
	'CHANGE'				=> '변경',
	'CHANGE_FONT_SIZE'		=> '폰트 크기 변경',
	'CHANGING_PREFERENCES'	=> '보드 기본 설정 변경',
	'CHANGING_PROFILE'		=> '프로필 설정 변경',
	'CHARACTERS'			=> array(
		1	=> '%d 문자',
		2	=> '%d 문자열',
	),
	'COLLAPSE_VIEW'			=> '보기 축소',
	'CLOSE_WINDOW'			=> '창 닫기',
	'CODE'					=> '코드',
	'COLOUR_SWATCH'			=> '색상 견본',
	'COLON'					=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> '확인',
	'CONFIRM_CODE'			=> '확인 코드',
	'CONFIRM_CODE_EXPLAIN'	=> '코드가 표시되는 대로 정확하게 입력하십시오. 모든 문자는 대소문자를 구분하지 않습니다.',
	'CONFIRM_CODE_WRONG'	=> '입력한 확인 코드가 잘못되었습니다.',
	'CONFIRM_OPERATION'		=> '이 작업을 수행하시겠습니까?',
	'CONFIRM_AVATAR_DELETE' => '이 아바타를 삭제하시겠습니까?',
	'CONGRATULATIONS'		=> '축하합니다',
	'CONNECTION_FAILED'		=> '연결실패.',
	'CONNECTION_SUCCESS'	=> '연결성공!',
	'CONTACT'				=> '연락처',
	'CONTACT_USER'			=> '연락처 %s',
	'CONTACT_US'			=> '문의하기',
	'COOKIE_CONSENT_INFO'	=> '자세히 알아보기',
	'COOKIE_CONSENT_MSG'	=> '이 웹사이트는 쿠키를 사용하여 웹사이트에서 최상의 경험을 얻을 수 있도록 합니다.',
	'COOKIE_CONSENT_OK'		=> '알았어요!(Got it!)',
	'COOKIE_CONSENT_HREF'	=> 'http://cookiesandyou.com',
	'COOKIES_DELETED'		=> '모든 보드 쿠키가 삭제되었습니다.',
	'CURRENT_TIME'			=> '현재 시각은 %s 입니다',

	'DAY'					=> '일',
	'DAYS'					=> '일',
	'DELETE'				=> '삭제',
	'DELETE_ALL'			=> '모두 삭제',
	'DELETE_COOKIES'		=> '쿠키 삭제',
	'DELETE_MARKED'			=> '삭제 표시',
	'DELETE_POST'			=> '글 삭제',
	'DELIMITER'				=> '구분자',
	'DESCENDING'			=> '내림차순',
	'DISABLED'				=> '비활성화',
	'DISPLAY'				=> '표시',
	'DISPLAY_GUESTS'		=> '손님 표시',
	'DISPLAY_MESSAGES'		=> '이전 메시지 표시',
	'DISPLAY_POSTS'			=> '이전 게시물 표시',
	'DISPLAY_TOPICS'		=> '이전 글 표시',
	'DOMAIN_NO_MX_RECORD_EMAIL'	=> '입력한 이메일 도메인에 유효한 MX 레코드가 없습니다.',
	'DOWNLOADED'			=> '다운로드됨',
	'DOWNLOADING_FILE'		=> '파일 다운로드 중',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> '아직 다운로드되지 않음',
		1	=> '%d번 다운로드됨',
		2	=> '%d번 다운로드됨',
	),

	'EDIT_POST'							=> '글 수정',
	'ELLIPSIS'							=>	'…',
	'EMAIL'								=> '이메일', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'						=> '이메일 주소',
	'EMAIL_INVALID_EMAIL'				=> '입력한 이메일 주소가 잘못되었습니다.',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> '<strong>%1$s행</strong>에서 이메일을 보내는 데 문제가 발생했습니다. 응답: %2$s.',
	'EMPTY_SUBJECT'						=> '새글을 게시할 때 글을 지정해야 합니다.',
	'EMPTY_MESSAGE_SUBJECT'				=> '새 메시지를 작성할 때 제목을 지정해야 합니다.',
	'ENABLED'							=> '활성화됨',
	'ENCLOSURE'							=> '인클로저',
	'ENTER_USERNAME'					=> '사용자 이름 입력',
	'ERR_CHANGING_DIRECTORY'			=> '디렉토리를 변경할 수 없습니다.',
	'ERR_CONNECTING_SERVER'				=> '서버에 연결하는 동안 오류가 발생했습니다.',
	'ERR_JAB_AUTH'						=> 'Jabber 서버에서 권한을 부여할 수 없습니다.',
	'ERR_JAB_CONNECT'					=> 'Jabber 서버에 연결할 수 없습니다.',
	'ERR_UNABLE_TO_LOGIN'				=> '지정된 사용자 이름 또는 암호가 올바르지 않습니다.',
	'ERR_UNWATCHING'					=> '구독 취소를 시도하는 동안 오류가 발생했습니다.',
	'ERR_WATCHING'						=> '구독을 시도하는 동안 오류가 발생했습니다.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> '지정된 phpBB 경로가 잘못된 것 같습니다.',
	'ERROR'									=> '애러',
	'EXPAND_VIEW'						=> '보기 확장',
	'EXTENSION'							=> '확대',
	'EXTENSION_DISABLED'				=> '확장 프로그램 <strong>%s</strong>이(가) 활성화되지 않았습니다.',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> '확장 프로그램 <strong>%s</strong>이(가) 비활성화되어 더 이상 표시할 수 없습니다.',
	'EXTENSION_DOES_NOT_EXIST'			=> '확장자 <strong>%s</strong>이(가) 존재하지 않습니다.',

	'FACEBOOK'				=> '페이스북',
	'FAQ'					=> 'FAQ',
	'FAQ_EXPLAIN'			=> '자주 묻는 질문',
	'FEATURE_NOT_AVAILABLE' => '요청한 기능은 이 게시판에서 사용할 수 없습니다',
	'FILENAME'				=> '파일이름',
	'FILESIZE'				=> '파일크기',
	'FILEDATE'				=> '파일날짜',
	'FILE_COMMENT'			=> '파일 댓글',
	'FILE_CONTENT_ERR'		=> '파일의 내용을 읽을 수 없음: %s',
	'FILE_JSON_DECODE_ERR'	=> 'json 파일 디코딩 실패: %s',
	'FILE_NOT_FOUND'		=> '요청한 파일을 찾을 수 없음: %s',
	'FIND_USERNAME'			=> '회원 찾기',
	'FOLDER'				=> '폴더',
	'FORGOT_PASS'			=> '비밀번호를 잊어버렸습니다.',
	'FORM_INVALID'			=> '제출된 양식이 잘못되었습니다. 다시 제출해 보세요',
	'FORUM'					=> '포럼',
	'FORUMS'				=> '포럼',
	'FORUMS_MARKED'			=> '포럼이 읽은 것으로 표시되었습니다.',
	'FORUM_CAT'				=> '포럼 카테고리',
	'FORUM_INDEX'			=> '보드 인덱스',
	'FORUM_LINK'			=> '포럼 링크',
	'FORUM_LOCATION'		=> '포럼 위치',
	'FORUM_LOCKED'			=> '포럼 잠김',
	'FORUM_RULES'			=> '포럼 규칙',
	'FORUM_RULES_LINK'		=> '포럼 규칙을 보려면 여기를 클릭하십시오.',
	'FROM'					=> '(으)로 부터',
	'FSOCK_DISABLED'		=> '<var>fsockopen</var> 기능이 비활성화되었거나 쿼리 중인 서버를 찾을 수 없기 때문에 작업을 완료할 수 없습니다.',
	'FSOCK_TIMEOUT'			=> '네트워크 스트림에서 읽는 동안 시간 초과가 발생했습니다.',

	'FILESYSTEM_CANNOT_CHANGE_FILE_GROUP'		=> '파일 그룹을 변경할 수 없습니다.',
	'FILESYSTEM_CANNOT_CHANGE_FILE_PERMISSIONS'	=> '파일 권한을 변경할 수 없습니다',
	'FILESYSTEM_CANNOT_COPY_FILES'				=> '파일을 복사할 수 없습니다',
	'FILESYSTEM_CANNOT_CREATE_SYMLINK'			=> '심볼릭 링크를 생성할 수 없습니다',
	'FILESYSTEM_CANNOT_CREATE_DIRECTORY'		=> '디렉토리를 생성할 수 없습니다',
	'FILESYSTEM_CANNOT_DELETE_FILES'			=> '시스템에서 파일을 삭제할 수 없습니다',
	'FILESYSTEM_CANNOT_DUMP_FILE'				=> '파일로 덤프할 수 없음',
	'FILESYSTEM_CANNOT_MIRROR_DIRECTORY'		=> '디렉터리를 미러링할 수 없습니다.',
	'FILESYSTEM_CANNOT_RENAME_FILE'				=> '시스템에서 파일 이름을 변경할 수 없습니다.',
	'FILESYSTEM_CANNOT_TOUCH_FILES'				=> '파일을 생성하거나 파일 타임스탬프를 변경할 수 없습니다.',

	'FTP_FSOCK_HOST'				=> 'FTP 호스트',
	'FTP_FSOCK_HOST_EXPLAIN'		=> '사이트를 연결하는 데 사용되는 FTP 서버입니다.',
	'FTP_FSOCK_PASSWORD'			=> 'FTP 비밀번호',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'FTP 사용자 이름의 비밀번호입니다.',
	'FTP_FSOCK_PORT'				=> 'FTP 포트',
	'FTP_FSOCK_PORT_EXPLAIN'		=> '서버에 연결하는 데 사용되는 포트입니다.',
	'FTP_FSOCK_ROOT_PATH'			=> 'phpBB 경로',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'root에서 phpBB 보드까지의 경로입니다.',
	'FTP_FSOCK_TIMEOUT'				=> 'FTP 시간 초과',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> '시스템이 서버의 응답을 기다리는 시간(초)입니다.',
	'FTP_FSOCK_USERNAME'			=> 'FTP 사용자이름',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> '서버에 연결하는 데 사용되는 사용자 이름입니다.',

	'FTP_HOST'					=> 'FTP 호스트',
	'FTP_HOST_EXPLAIN'			=> '사이트를 연결하는 데 사용되는 FTP 서버입니다.',
	'FTP_PASSWORD'				=> 'FTP 비밀번호',
	'FTP_PASSWORD_EXPLAIN'		=> 'FTP 사용자 이름의 비밀번호입니다.',
	'FTP_PORT'					=> 'FTP 포트',
	'FTP_PORT_EXPLAIN'			=> '서버에 연결하는 데 사용되는 포트입니다.',
	'FTP_ROOT_PATH'				=> 'phpBB 경로',
	'FTP_ROOT_PATH_EXPLAIN'		=> 'root에서 phpBB 보드까지의 경로입니다.',
	'FTP_TIMEOUT'				=> 'FTP 시간초과',
	'FTP_TIMEOUT_EXPLAIN'		=> '시스템이 서버의 응답을 기다리는 시간(초)입니다.',
	'FTP_USERNAME'				=> 'FTP 사용자이름',
	'FTP_USERNAME_EXPLAIN'		=> '서버에 연결하는 데 사용되는 사용자 이름입니다.',

	'GENERAL_ERROR'				=> '일반 오류',
	'GB'						=> 'GB',
	'GIB'						=> 'GiB',
	'GO'						=> '이동',
	'GOTO_FIRST_POST'			=> '첫 번째 게시물로 이동',
	'GOTO_LAST_POST'			=> '지난 게시물로 이동',
	'GOTO_PAGE'					=> '페이지로 이동',
	'GROUP'						=> '그룹',
	'GROUPS'					=> '그룹',
	'GROUP_ERR_TYPE'			=> '부적절한 그룹 유형이 지정되었습니다',
	'GROUP_ERR_USERNAME'		=> '그룹 이름이 지정되지 않았습니다.',
	'GROUP_ERR_USER_LONG'		=> '그룹 이름은 60자를 초과할 수 없습니다. 지정한 그룹 이름이 너무 깁니다.',
	'GUEST'						=> '손님',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> '손님 %d명이 접속 중입니다',
		2	=> '손님 %d명이 접속 중입니다',
	),
	'GUEST_USERS_TOTAL'			=> array(
		1	=> '손님 %d명',
		2	=> '손님 %d명',
	),
	'G_ADMINISTRATORS'			=> '관리자',
	'G_BOTS'					=> '봇',
	'G_GUESTS'					=> '손님',
	'G_REGISTERED'				=> '가입자',
	'G_REGISTERED_COPPA'		=> 'COPPA 가입자',  // Children's Online Privacy Protection Act, 우리나라 청소년 보호법이랑 비슷
	'G_GLOBAL_MODERATORS'		=> '총괄운영자',
	'G_NEWLY_REGISTERED'		=> '신규가입자',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '비공개 접속자 %d명',
		2	=> '비공개 접속자 %d명',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '비공개 사용자 %d명',
		2	=> '비공개 사용자 %d명',
	),
	'HIDE_GUESTS'					=> '손님 비공개하기',
	'HIDE_ME'						=> '접속상태를 비공개하고 로그인하기',
	'HOURS'							=> '시간',
	'HOME'							=> '홈',

	'ICQ'						=> 'ICQ',
	'IF'						=> '만약',
	'IMAGE'						=> '이미지',
	'IMAGE_FILETYPE_INVALID'	=> '%s 모형의 이미지 파일 형식 %d이(가) 지원되지 않습니다.',
	'IMAGE_FILETYPE_MISMATCH'	=> '이미지 파일 형식이 일치하지 않습니다. 확장자는 %1$s이지만 확장자는 %2$s이(가) 지정되었습니다.',
	'IN'						=> '안에',
	'INACTIVE'					=> '비활성',
	'INDEX'						=> '인덱스 페이지',
	'INFORMATION'				=> '정보',
	'INSECURE_REDIRECT'			=> '잠재적으로 안전하지 않은 URL로 리디렉션을 시도했습니다.',
	'INTERESTS'					=> '관심사',
	'INVALID_DIGEST_CHALLENGE'	=> '잘못된 다이제스트 챌린지',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> 이메일 주소가 잘못되었을 수 있습니까?',
	'INVALID_FEED_ATTACHMENTS'	=> '선택한 피드에서 제약 조건이 잘못된 첨부파일을 가져오려고 했습니다.',
	'INVALID_PLURAL_RULE'		=> '선택한 복수형 규칙이 잘못되었습니다. 유효한 값은 0~15 사이의 정수입니다.',
	'IP'						=> 'IP',
	'IP_BLACKLISTED'			=> '귀하의 IP %1$s은(는) 차단 목록에 포함되어 차단되었습니다. 자세한 내용은 <a href="%2$s">%2$s</a>를 참조하세요.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> '가입',
	'JUMP_PAGE'				=> '이동하려는 페이지 번호를 입력하세요.',
	'JUMP_TO'				=> '이동',
	'JUMP_TO_PAGE'			=> '페이지로 이동',
	'JUMP_TO_PAGE_CLICK'	=> '클릭하면 페이지로 이동…',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'							=> '마지막 게시물',
	'LAST_UPDATED'						=> '마지막 업데이트',
	'LAST_VISIT'						=> '마지막 방문',
	'LDAP_NO_LDAP_EXTENSION'			=> 'LDAP 확장을 사용할 수 없습니다.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'LDAP 서버에 연결할 수 없습니다.',
	'LDAP_SEARCH_FAILED'				=> 'LDAP 디렉토리를 검색하는 동안 오류가 발생했습니다.',
	'LEGEND'							=> '명예그룹',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> '실시간 검색은 허용되지 않습니다.',
	'LOADING'							=> '로딩',
	'LOCATION'							=> '위치',
	'LOCK_POST'							=> '게시 잠금',
	'LOCK_POST_EXPLAIN'					=> '수정 금지',
	'LOCK_TOPIC'						=> '글 잠금',
	'LOGIN'								=> '로그인',
	'LOGIN_CHECK_PM'					=> '로그인하여 비공개 메시지를 확인하세요.',
	'LOGIN_CONFIRMATION'				=> '로그인 확인',
	'LOGIN_CONFIRM_EXPLAIN'				=> '무차별 대입 계정을 방지하기 위해 보드는 최대 로그인 실패 후 확인 코드를 입력하도록 요구합니다. 코드는 아래에 표시되어야 하는 이미지에 표시됩니다. 시각 장애가 있거나 이 코드를 읽을 수 없는 경우 %s보드 관리자%s에게 문의하십시오.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> '허용된 최대 로그인 시도 횟수를 초과했습니다. 사용자 이름과 비밀번호 외에도 이제 보안 문자 테스트를 통과해야 합니다.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'Apache에서 인증하지 않았습니다.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> '존재하지 않는 OAuth 서비스가 요청되었습니다.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> '이 게시판의 소프트웨어를 업데이트할 때 비밀번호를 변환할 수 없습니다. %s새 비밀번호를 요청하십시오%s. 문제가 계속되면 %s보드 관리자%s에게 문의하십시오.',
	'LOGIN_ERROR_USERNAME'				=> '잘못된 사용자 이름을 지정했습니다. 사용자 이름을 확인하고 다시 시도하십시오. 문제가 계속되면 %s보드 관리자%s에게 문의하십시오.',
	'LOGIN_FORUM'						=> '이 포럼을 보거나 게시하려면 비밀번호를 입력해야 합니다.',
	'LOGIN_INFO'						=> '로그인을 하기 위해서는 회원가입을 하셔야 합니다. 등록하는 데 몇 분 밖에 걸리지 않지만 향상된 기능을 제공합니다. 게시판 관리자는 정식사용자에게 추가 권한을 부여할 수도 있습니다. 등록하기 전에 당사의 이용 약관 및 관련 정책을 숙지하시기 바랍니다. 게시판을 탐색할 때 포럼 규칙을 모두 읽으십시오.',
	'LOGIN_VIEWFORUM'					=> '이 포럼을 보려면 보드에 등록하고 로그인해야 합니다.',
	'LOGIN_EXPLAIN_EDIT'				=> '이 포럼의 게시물을 편집하려면 등록 및 로그인해야 합니다.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> '온라인 목록을 보려면 등록 및 로그인해야 합니다.',
	'LOGIN_REQUIRED'					=> '이 작업을 수행하려면 로그인해야 합니다.',
	'LOGOUT'							=> '로그아웃',
	'LOGOUT_USER'						=> '로그아웃 [%s]',
	'LOG_ME_IN'							=> '기억하기',

	'MAIN'					=> '매인',
	'MARK'					=> '표시',
	'MARK_ALL'				=> '모두 표시',
	'MARK_ALL_READ'			=> '모두 읽은 것으로 표시',
	'MARK_FORUMS_READ'		=> '읽은 포럼으로 표시',
	'MARK_READ'				=> '읽은 것으로 표시',
	'MARK_SUBFORUMS_READ'	=> '읽은 하위 포럼 표시',
	'MB'					=> 'MB',
	'MIB'					=> 'MiB',
	'MCP'					=> '운영자 컨트롤 패널',
	'MCP_SHORT'				=> 'MCP',
	'MEMBERLIST'			=> '회원',
	'MEMBERLIST_EXPLAIN'	=> '전체 회원 목록 보기',
	'MERGE'					=> '병합',
	'MERGE_POSTS'			=> '게시물 이동',
	'MERGE_TOPIC'			=> '글 병합',
	'MESSAGE'				=> '메세지',
	'MESSAGES'				=> '메세지',
	'MESSAGES_COUNT'		=> array(
		1	=> '%d 메세지',
		2	=> '%d 메세지',
	),
	'MESSAGE_BODY'			=> '메시지 본문',
	'MINUTES'				=> '분',
	'MODERATE'				=> '보통',
	'MODERATOR'				=> '운영자',
	'MODERATORS'			=> '운영자',
	'MODULE_NOT_ACCESS'		=> '모듈에 접근할 수 없음',
	'MODULE_NOT_FIND'		=> '모듈 %s을(를) 찾을 수 없습니다.',
	'MODULE_FILE_INCORRECT_CLASS'	=> '모듈 파일 %s에 올바른 클래스 [%s]이(가) 포함되어 있지 않습니다.',
	'MONTH'					=> '월',
	'MOVE'					=> '이동',

	'NA'						=> 'N/A',
	'NEWEST_USER'				=> '신규 회원 <strong>%s</strong>',
	'NEW_MESSAGE'				=> '새로운 메시지',
	'NEW_MESSAGES'				=> '새로운 메시지',
	'NEW_POST'					=> '새로운 게시물',	// Not used anymore
	'NEW_POSTS'					=> '새로운 게시물',	// Not used anymore
	'NEXT'						=> '다음',		// Used in pagination
	'NEXT_STEP'					=> '다음',
	'NEVER'						=> '없음',
	'NO'						=> '아니오',
	'NO_NOTIFICATIONS'			=> '알림이 없습니다.',
	'NOT_ALLOWED_MANAGE_GROUP'	=> '이 그룹을 관리할 수 없습니다.',
	'NOT_AUTHORISED'			=> '이 영역에 액세스할 수 있는 권한이 없습니다.',
	'NOT_WATCHING_FORUM'		=> '더 이상 이 포럼의 업데이트를 구독하지 않습니다.',
	'NOT_WATCHING_TOPIC'		=> '더 이상 이 글을 구독하지 않습니다.',
	'NOTIFICATIONS'				=> '알림',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '북마크된 글을 %1$s에서 <strong>답장</strong>:',
	),
	'NOTIFICATION_FORUM'				=> '<em>포럼:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '%1$s의 <strong>그룹 요청</strong>이 %2$s 그룹에 가입했습니다.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '%1$s 그룹에 가입하기 위한 <strong>그룹 요청이 승인되었습니다</strong>.',
	'NOTIFICATION_METHOD_INVALID'		=> '"%s" 메서드는 유효한 알림 메서드를 참조하지 않습니다.',
	'NOTIFICATION_PM'					=> '%1$s의 <strong>비공개 메시지</strong>:',
	'NOTIFICATION_POST'					=> array(
		1	=> '글을 %1$s에서 <strong>답장</strong>:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>게시물 승인</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>비승인된 게시물</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '%1$s의 <strong>게시 승인</strong> 요청:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '<strong>인용</strong>: %1$s:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'				=> '<em>원인:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '%1$s님이 보고한 <strong>비공개 메시지</strong>:',
	'NOTIFICATION_REPORT_PM_CLOSED'		=> '%1$s에 의해 <strong>비공개 메시지 보고서가 종료되었습니다</strong>:',
	'NOTIFICATION_REPORT_POST'			=> '%1$s님이 <strong>신고한 게시물</strong>:',
	'NOTIFICATION_REPORT_CLOSED'		=> '%1$s에 의해 <strong>보고서 종료</strong>:',
	'NOTIFICATION_TOPIC'				=> '<strong>새글</strong> 작성자: %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>승인된 글</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>비승인된 글</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '%1$s님의 <strong>글 승인</strong> 요청:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> '알림 유형 "%s"이 파일 시스템에 없습니다.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '비활성화되거나 미인증 사용자의 <strong>활성화 필요</strong>: "%1$s"',
	// Used in conjunction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> '기타',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '%d 기타',
	),
	'NOTIFY_ADMIN'				=> '보드 관리자나 웹마스터에게 알려주세요.',
	'NOTIFY_ADMIN_EMAIL'		=> '보드 관리자 또는 웹마스터에게 다음 사항을 알리십시오. <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> '이 파일에 액세스할 수 없습니다.',
	'NO_ACTION'					=> '지정된 작업이 없습니다.',
	'NO_ADMINISTRATORS'			=> '관리자가 없습니다.',
	'NO_AUTH_ADMIN'				=> '관리 권한이 없으므로 관리 제어판에 대한 액세스가 허용되지 않습니다.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> '다른 사용자로 재인증할 수 없습니다.',
	'NO_AUTH_OPERATION'			=> '이 작업을 완료하는 데 필요한 권한이 없습니다.',
	'NO_AVATARS'				=> '현재 사용 가능한 아바타가 없습니다.',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'smtp 호스트에 연결할 수 없음: %1$s: %2$s',
	'NO_BIRTHDAYS'				=> '오늘의 생일자는 없습니다',
	'NO_EMAIL_MESSAGE'			=> '이메일 메시지가 비어 있습니다.',
	'NO_EMAIL_RESPONSE_CODE'	=> '메일 서버 응답 코드를 가져올 수 없습니다.',
	'NO_EMAIL_SUBJECT'			=> '이메일 제목이 지정되지 않았습니다.',
	'NO_FORUM'					=> '선택한 포럼이 존재하지 않습니다.',
	'NO_FORUMS'					=> '이 보드에는 포럼이 없습니다.',
	'NO_GROUP'					=> '요청한 사용자 그룹이 존재하지 않습니다.',
	'NO_GROUP_MEMBERS'			=> '이 그룹에는 현재 회원이 없습니다.',
	'NO_IPS_DEFINED'			=> 'IP 주소 또는 호스트 이름이 정의되지 않았습니다.',
	'NO_MEMBERS'				=> '이 검색 기준에 대한 회원을 찾을 수 없습니다.',
	'NO_MESSAGES'				=> '메시지 없음',
	'NO_MODE'					=> '지정된 모드가 없습니다.',
	'NO_MODERATORS'				=> '운영자가 없습니다.',
	'NO_NEW_MESSAGES'			=> '새 메시지 없음',
	'NO_NEW_POSTS'				=> '새 게시물이 없습니다.',	// Not used anymore
	'NO_ONLINE_USERS'			=> '접속중인 가입자가 없습니다',
	'NO_POSTS'					=> '게시물 없음',
	'NO_POSTS_TIME_FRAME'		=> '선택한 기간 동안 이 글 내에 게시물이 없습니',
	'NO_FEED_ENABLED'			=> '이 게시판에는 피드가 없습니다.',
	'NO_FEED'					=> '요청한 피드를 사용할 수 없습니다.',
	'NO_STYLE_DATA'				=> '사용자 스타일에 대한 스타일 데이터를 가져올 수 없으며 사용자 ID %s에 대해 설정할 수 있습니다.',
	'NO_STYLE_CFG'				=> '%s에 대한 스타일 구성 파일을 가져올 수 없습니다.',
	'NO_SUBJECT'				=> '지정된 글 없음',								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> '지정된 검색 백엔드가 존재하지 않습니다.',
	'NO_SUPPORTED_AUTH_METHODS'	=> '지원되는 인증 방법이 없습니다.',
	'NO_TOPIC'					=> '요청한 글이 존재하지 않습니다.',
	'NO_TOPIC_FORUM'			=> '글 또는 포럼이 더 이상 존재하지 않습니다.',
	'NO_TOPICS'					=> '이 포럼에는 글이나 게시물이 없습니다.',
	'NO_TOPICS_TIME_FRAME'		=> '선택한 기간 동안 이 포럼에 글이 없습니다.',
	'NO_UNREAD_POSTS'			=> '읽지 않은 게시물이 없습니다.',
	'NO_UPLOAD_FORM_FOUND'		=> '업로드가 시작되었지만 유효한 파일 업로드 양식이 없습니다.',
	'NO_USER'					=> '요청한 사용자가 존재하지 않습니다.',
	'NO_USERS'					=> '요청한 사용자가 존재하지 않습니다.',
	'NO_USER_SPECIFIED'			=> '사용자 이름이 지정되지 않았습니다.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d 첨부파일',
		2	=> '%d 첨부파일',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> '대기열에 게시물이 없습니다',		// 0
		1			=> '대기열에 있는 게시물 1개',		// 1
		2			=> '대기열에 있는 %d개의 게시물',		// 2+
	),

	'OCCUPATION'				=> '직업',
	'OFFLINE'					=> '오프라인',
	'ONLINE'					=> '온라인',
	'ONLINE_BUDDIES'			=> '온라인 친구',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> '총 <strong>%1$d</strong>명이 접속 중입니다 :: %2$s 및 %3$s',
		2	=> '총 <strong>%1$d</strong>명이 접속 중입니다 :: %2$s 및 %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> '총 <strong>%1$d</strong>명이 접속 중입니다 :: %2$s, %3$s 및 %4$s',
		2	=> '총 <strong>%1$d</strong>명이 접속 중입니다 :: %2$s, %3$s 및 %4$s',
	),
	'OPTIONS'					=> '옵션',

	'PAGE_NOT_FOUND'		=> '요청하신 페이지를 찾을 수 없습니다.',
	'PAGE_OF'				=> '<strong>%2$d</strong> 중 <strong>%1$d</strong> 페이지',
	'PAGE_TITLE_NUMBER'		=> '페이지 %s',
	'PASSWORD'				=> '비밀번호',
	'PIXEL'					=> 'px',
	'PIXELS'				=> array(
		1	=> '%d 픽셀',
		2	=> '%d 픽셀',
	),
	'PLEASE_WAIT'			=> '기다려 주십시오.',
	'PM'					=> 'PM',
	'PM_REPORTED'			=> '보고서를 보려면 클릭하세요.',
	'POSTING_MESSAGE'		=> '%s에 메시지 게시',
	'POSTING_PRIVATE_MESSAGE'	=> '비공개 메시지 작성',
	'POST'					=> '올림',
	'POST_ANNOUNCEMENT'		=> '포럼공지',
	'POST_STICKY'			=> '상위 고정',
	'POSTED'				=> '게시됨',
	'POSTED_IN_FORUM'		=> 'in',
	'POSTED_ON_DATE'		=> 'on',
	'POSTS'					=> '게시물',
	'POSTS_UNAPPROVED'		=> '이 글에서 하나 이상의 게시물이 승인되지 않았습니다.',
	'POSTS_UNAPPROVED_FORUM'=> '이 포럼에서 하나 이상의 게시물이 승인되지 않았습니다.',
	'POST_BY_AUTHOR'		=> '작성자 :',
	'POST_BY_FOE'			=> '현재 무시 목록에 있는 <strong>%1$s</strong>님이 이 게시물을 작성했습니다.',
	'POST_DISPLAY'			=> '%1$s이 게시물%2$s 표시',
	'POST_DAY'				=> '하루에 %.2f개의 게시물',
	'POST_DELETED_ACTION'	=> '삭제된 게시물:',
	'POST_DELETED'			=> '이 게시물은 삭제되었습니다.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong>님이 %3$s에서 <strong>%1$s</strong>님의 게시물을 삭제했습니다.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong>님이 다음과 같은 사유로 %3$s에서 <strong>%1$s</strong>의 게시물을 삭제했습니다. %4$s',
	'POST_DETAILS'			=> '게시물 세부정보',
	'POST_NEW_TOPIC'		=> '새글 작성',
	'POST_PCT'				=> '모든 게시물의 %.2f%%',
	'POST_PCT_ACTIVE'		=> '사용자 게시물의 %.2f%%',
	'POST_PCT_ACTIVE_OWN'	=> '게시물의 %.2f%%',
	'POST_REPLY'			=> '답글 게시',
	'POST_REPORTED'			=> '보고서를 보려면 클릭하세요.',
	'POST_SUBJECT'			=> '게시물 제목',
	'POST_TIME'				=> '게시 시간',
	'POST_TOPIC'			=> '새글 작성',
	'POST_UNAPPROVED_ACTION'	=> '승인 대기 중인 게시물:',
	'POST_UNAPPROVED'		=> '이 게시물은 승인되지 않았습니다.',
	'POST_UNAPPROVED_EXPLAIN'	=> '이 게시물은 운영자가 승인할 때까지 다른 사용자에게 표시되지 않습니다.',
	'POWERED_BY'			=> '%s 제공',

	'QUOTE'					=> '인용문',

	'PREVIEW'				=> '미리보기',
	'PREVIOUS'				=> '이전',		// Used in pagination
	'PREVIOUS_STEP'			=> '이전',
	'PRIVACY'				=> '개인 정보 정책',
	'PRIVACY_LINK'			=> '개인 정보',
	'PRIVATE_MESSAGE'		=> '개인 메시지',
	'PRIVATE_MESSAGES'		=> '개인 메시지',
	'PRIVATE_MESSAGING'		=> '개인 메시지',
	'PROFILE'				=> '사용자 제어판',

	'QUICK_LINKS'			=> '빠른 링크',

	'RANK'						=> '순위',
	'READING_FORUM'				=> '%s의 글 보는 중',
	'READING_GLOBAL_ANNOUNCE'	=> '전체공지 읽는 중',
	'READING_LINK'				=> '포럼 링크 %s 따라가는 중',
	'READING_TOPIC'				=> '%s에서 글 읽는 중',
	'READ_PROFILE'				=> '프로필',
	'REASON'					=> '사유',
	'RECORD_ONLINE_USERS'		=> '최다 동시접속자 기록 <strong>%1$s</strong>명 %2$s',
	'REDIRECT'					=> '리디렉션',
	'REDIRECTS'					=> '총 리디렉션',
	'REGISTER'					=> '가입',
	'REGISTERED_USERS'			=> '가입자:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> '가입자 %1$d명과 %2$s이 접속 중입니다',
		2	=> '가입자 %1$d명과 %2$s이 접속 중입니다',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '가입자 %d명',
		2	=> '가입자 %d명',
	),
	'REMOVE'					=> '제거하다',
	'REMOVE_INSTALL'			=> '보드를 사용하기 전에 설치 디렉토리를 삭제, 이동 또는 이름을 변경하십시오. 이 디렉토리가 여전히 존재하면 ACP(관리 제어판)에만 액세스할 수 있습니다.',
	'REPLIES'					=> '답글',
	'REPLY_WITH_QUOTE'			=> '인용문으로 답장',
	'REPLYING_GLOBAL_ANNOUNCE'	=> '글로벌 발표에 응답하기',
	'REPLYING_MESSAGE'			=> '%s의 메시지에 답장하는 중',
	'REPORT_BY'					=> '보고자',
	'REPORT_POST'				=> '이 게시물 신고',
	'REPORTING_POST'			=> '게시물 신고',
	'RESEND_ACTIVATION'			=> '활성화 이메일 재전송',
	'RESET'						=> '리셋',
	'RESTORE_PERMISSIONS'		=> '권한 복원',
	'RETURN_INDEX'				=> '%s인덱스 페이지로 돌아가기%s',
	'RETURN_FORUM'				=> '%s마지막으로 방문한 포럼으로 돌아가기%s',
	'RETURN_PAGE'				=> '%s이전 페이지로 돌아가기%s',
	'RETURN_TOPIC'				=> '%s마지막으로 방문한 글로 돌아가기%s',
	'RETURN_TO'					=> '"%s"로 돌아가기',
	'RETURN_TO_INDEX'			=> '보드 인덱스로 돌아가기',
	'FEED'						=> '피드',
	'FEED_NEWS'					=> '뉴스',
	'FEED_TOPICS_ACTIVE'		=> '활성 글',
	'FEED_TOPICS_NEW'			=> '새글',
	'RULES_ATTACH_CAN'			=> '이 포럼에 첨부파일을 <strong>게시할 수 있습니다</strong>',
	'RULES_ATTACH_CANNOT'		=> '이 포럼에 첨부파일을 <strong>게시할 수 없습니다</strong>',
	'RULES_DELETE_CAN'			=> '이 포럼에서 게시물을 <strong>삭제할 수 있습니다</strong>',
	'RULES_DELETE_CANNOT'		=> '이 포럼에서 게시물을 <strong>삭제할 수 없습니다</strong>',
	'RULES_DOWNLOAD_CAN'		=> '이 포럼에서 첨부파일을 <strong>다운로드할 수 있습니다</strong>',
	'RULES_DOWNLOAD_CANNOT'		=> '이 포럼에서 첨부파일을 <strong>다운로드할 수 없습니다</strong>',
	'RULES_EDIT_CAN'			=> '이 포럼에서 게시물을 <strong>수정할 수 있습니다</strong>',
	'RULES_EDIT_CANNOT'			=> '이 포럼에서 게시물을 <strong>수정할 수 없습니다</strong>',
	'RULES_LOCK_CAN'			=> '이 포럼에서 글을 <strong>잠글 수 있습니다</strong>',
	'RULES_LOCK_CANNOT'			=> '이 포럼에서 글을 <strong>잠글 수 없습니다</strong>',
	'RULES_POST_CAN'			=> '이 포럼에 새글을 <strong>게시할 수 있습니다</strong>',
	'RULES_POST_CANNOT'			=> '이 포럼에 새글을 <strong>게시할 수 없습니다</strong>',
	'RULES_REPLY_CAN'			=> '이 포럼의 글에 <strong>응답할 수 있습니다</strong>',
	'RULES_REPLY_CANNOT'		=> '이 포럼의 글에 <strong>답글을 달 수 없습니다</strong>',
	'RULES_VOTE_CAN'			=> '이 포럼의 투표에 <strong>할 수 있습니다</strong>',
	'RULES_VOTE_CANNOT'			=> '이 포럼의 투표에 <strong>할 수 없습니다</strong>',

	'SEARCH'					=> '검색',
	'SEARCH_MINI'				=> '검색…',
	'SEARCH_ADV'				=> '고급 검색',
	'SEARCH_ADV_EXPLAIN'		=> '고급 검색 옵션 보기',
	'SEARCH_KEYWORDS'			=> '키워드 검색',
	'SEARCHING_FORUMS'			=> '포럼 검색',
	'SEARCH_ACTIVE_TOPICS'		=> '할성화된 글',
	'SEARCH_FOR'				=> '검색',
	'SEARCH_FORUM'				=> '이 포럼 검색…',
	'SEARCH_NEW'				=> '새 게시물',
	'SEARCH_POSTS_BY'			=> '게시물 검색',
	'SEARCH_SELF'				=> '내 게시물',
	'SEARCH_TOPIC'				=> '이 글 검색…',
	'SEARCH_UNANSWERED'			=> '답변이 없는 글',
	'SEARCH_UNREAD'				=> '읽지 않은 게시물',
	'SEARCH_USER_POSTS'			=> '사용자의 게시물 검색',
	'SECONDS'					=> '초',
	'SEE_ALL'					=> '모두 보기',
	'SELECT'					=> '선택',
	'SELECT_ALL_CODE'			=> '모두 선택',
	'SELECT_DESTINATION_FORUM'	=> '대상 포럼을 선택하십시오',
	'SELECT_FORUM'				=> '포럼 선택',
	'SEND_EMAIL'				=> '메일 보내기',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> '%s에게 메일 보내기',
	'SEND_PRIVATE_MESSAGE'		=> '비공개 메시지 보내기',
	'SETTINGS'					=> '설정',
	'SIGNATURE'					=> '서명',
	'SKIP'						=> '내용으로 건너뛰기',
	'SKYPE'						=> '스카이프',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP 서버는 인증을 지원하지 않습니다.',
	'SORRY_AUTH_READ'			=> '이 포럼을 읽을 권한이 없습니다.',
	'SORRY_AUTH_READ_TOPIC'		=> '이 글을 읽을 권한이 없습니다',
	'SORRY_AUTH_VIEW_ATTACH'	=> '이 첨부파일을 다운로드할 권한이 없습니다.',
	'SORT_BY'					=> '정렬 기준',
	'SORT_DIRECTION'			=> '방향',
	'SORT_JOINED'				=> '가입 날짜',
	'SORT_LOCATION'				=> '위치',
	'SORT_OPTIONS'				=> '표시 및 정렬 옵션',
	'SORT_RANK'					=> '순위',
	'SORT_POSTS'				=> '게시자',
	'SORT_TOPIC_TITLE'			=> '글 제목',
	'SORT_USERNAME'				=> '사용자 이름',
	'SPLIT_TOPIC'				=> '글 분할',
	'SQL_ERROR_OCCURRED'		=> '이 페이지를 가져오는 동안 SQL 오류가 발생했습니다. 이 문제가 지속되면 %s보드 관리자%s에게 문의하십시오.',
	'STATISTICS'				=> '통계',
	'START_WATCHING_FORUM'		=> '포럼 구독',
	'START_WATCHING_TOPIC'		=> '글 구독',
	'STOP_WATCHING_FORUM'		=> '포럼 구독 취소',
	'STOP_WATCHING_TOPIC'		=> '글 구독 취소',
	'STRING_LIST_MULTI'			=> '%1$s 및 %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s 그리고 %2$s',
	'SUBFORUM'					=> '하위 포럼',
	'SUBFORUMS'					=> '하위 포럼',
	'SUBJECT'					=> '재목',
	'SUBMIT'					=> '제출',

	'TB'				=> 'TB',
	'TERMS_LINK'		=> '약관',
	'TERMS_USE'			=> '이용약관',
	'TEST_CONNECTION'	=> '연결 테스트',
	'THE_TEAM'			=> '운영진',
	'TIB'				=> 'TiB',
	'TIME'				=> '시간',
	'TIMEOUT_PROCESSING_REQ'			=> '요청 시간이 초과되었습니다.',

	'TOO_LARGE'						=> '입력한 값이 너무 큽니다.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> '입력한 <strong>비공개 메시지당 허용되는 최대 수신자 수</strong> 설정 값이 너무 큽니다.',

	'TOO_LONG'						=> '입력한 값이 너무 깁니다.',

	'TOO_LONG_CONFIRM_CODE'			=> '입력한 확인 코드가 너무 깁니다.',
	'TOO_LONG_DATEFORMAT'			=> '입력한 날짜 형식이 너무 깁니다.',
	'TOO_LONG_JABBER'				=> '입력한 Jabber 계정 이름이 너무 깁니다.',
	'TOO_LONG_NEW_PASSWORD'			=> '입력한 비밀번호가 너무 깁니다.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> '입력한 비밀번호 확인이 너무 깁니다.',
	'TOO_LONG_USER_PASSWORD'		=> '입력한 비밀번호가 너무 깁니다.',
	'TOO_LONG_USERNAME'				=> '입력한 사용자 이름이 너무 깁니다.',
	'TOO_LONG_EMAIL'				=> '입력한 이메일 주소가 너무 깁니다',

	'TOO_MANY_VOTE_OPTIONS'			=> '너무 많은 옵션에 투표하려고 했습니다.',

	'TOO_SHORT'						=> '입력한 값이 너무 짧습니다.',

	'TOO_SHORT_CONFIRM_CODE'		=> '입력한 확인 코드가 너무 짧습니다.',
	'TOO_SHORT_DATEFORMAT'			=> '입력한 날짜 형식이 너무 짧습니다.',
	'TOO_SHORT_JABBER'				=> '입력한 Jabber 계정 이름이 너무 짧습니다.',
	'TOO_SHORT_NEW_PASSWORD'		=> '입력한 비밀번호가 너무 짧습니다.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> '입력한 비밀번호 확인이 너무 짧습니다.',
	'TOO_SHORT_USER_PASSWORD'		=> '입력한 비밀번호가 너무 짧습니다.',
	'TOO_SHORT_USERNAME'			=> '입력한 사용자 이름이 너무 짧습니다.',
	'TOO_SHORT_EMAIL'				=> '입력한 이메일 주소가 너무 짧습니다.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> '입력한 확인 이메일 주소가 너무 짧습니다.',
	'TOO_SMALL'						=> '입력한 값이 너무 작습니다.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> '입력한 <strong>비공개 메시지당 허용되는 최대 수신자 수</strong> 설정 값이 너무 작습니다.',

	'TOPIC'				=> '글',
	'TOPICS'			=> '글',
	'TOPICS_UNAPPROVED'	=> '이 포럼에서 하나 이상의 글이 승인되지 않았습니다.',
	'TOPIC_ICON'		=> '글 아이콘',
	'TOPIC_LOCKED'		=> '이 글은 잠겨 있어 게시물을 편집하거나 추가로 답글을 달 수 없습니다.',
	'TOPIC_LOCKED_SHORT'=> '글 잠김',
	'TOPIC_MOVED'		=> '이동된 글',
	'TOPIC_REVIEW'		=> '글 검토',
	'TOPIC_TITLE'		=> '글 제목',
	'TOPIC_UNAPPROVED'	=> '이 글은 승인되지 않았습니다.',
	'TOPIC_UNAPPROVED_FORUM'	=> array(
		1	=> '승인 대기 중인 글',
		2	=> '승인 대기 중인 글',
	),
	'TOPIC_DELETED'		=> '이 글은 삭제되었습니다.',
	'TOTAL_ATTACHMENTS'	=> '첨부파일',
	'TOTAL_LOGS'		=> array(
		1	=> '%d log',
		2	=> '%d logs',
	),
	'TOTAL_PMS'		=> array(
		1	=> '총 %d개의 비공개 메시지',
		2	=> '총 %d개의 비공개 메시지',
	),
	'TOPIC_POLL'		=> '이 글에는 설문조사가 있습니다',
	'TOTAL_POSTS'		=> '총 게시물',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> '총 게시물 <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> '이 글은 보고되었습니다',
	'TOTAL_TOPICS'		=> array(
		2	=> '총 글 <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		2	=> '총 회원 <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=> '추적된 PHP 오류: %s',
	'TWITTER'			=> '트위터',

	'UNABLE_GET_IMAGE_SIZE'	=> '이미지의 크기를 결정할 수 없습니다. 입력한 URL이 올바른지 확인하십시오.',
	'UNABLE_TO_DELIVER_FILE'=> '파일을 전달할 수 없습니다.',
	'UNKNOWN_BROWSER'		=> '알 수 없는 브라우저',
	'UNMARK_ALL'			=> '모두 표시 해제',
	'UNREAD_MESSAGES'		=> '읽지 않은 메시지',
	'UNREAD_POST'			=> '읽지 않은 게시물',
	'UNREAD_POSTS'			=> '읽지 않은 게시물',
	'UNWATCH_FORUM_CONFIRM'		=> '이 포럼에서 구독을 취소하시겠습니',
	'UNWATCH_FORUM_DETAILED'	=> '"%s" 포럼 구독을 취소하시겠습니까?',
	'UNWATCH_TOPIC_CONFIRM'		=> '이 글을 구독을 취소하시겠습니까?',
	'UNWATCH_TOPIC_DETAILED'	=> '"%s" 글을 구독을 취소하시겠습니까?',
	'UNWATCHED_FORUMS'			=> '선택한 포럼에 더 이상 가입되어 있지 않습니다.',
	'UNWATCHED_TOPICS'			=> '더 이상 선택한 글을 구독하지 않습니다.',
	'UNWATCHED_FORUMS_TOPICS'	=> '더 이상 선택한 항목에 가입되어 있지 않습니다.',
	'UPDATE'				=> '업데이트',
	'UPLOAD_IN_PROGRESS'	=> '현재 업로드가 진행 중입니다.',
	'URL_REDIRECT'			=> '브라우저가 메타 리디렉션 %s을(를) 지원하지 않는 경우 리디렉션하려면 여기를 클릭하십시오%s.',
	'USERGROUPS'			=> '그룹',
	'USERNAME'				=> '사용자 이름',
	'USERNAMES'				=> '사용자 이름',
	'USER_AVATAR'			=> '사용자 아바타',
	'USER_CANNOT_READ'		=> '이 포럼의 게시물을 읽을 수 없습니다.',
	'USER_POSTS'			=> array(
		1	=> '%d 게시물',
		2	=> '%d 게시물',
	),
	'USERS'					=> '시용자',
	'USE_PERMISSIONS'		=> '관리자 권한 이전',

	'USER_NEW_PERMISSION_DISALLOWED'	=> '죄송합니다. 이 기능을 사용할 권한이 없습니다. 여기에서 방금 등록했으며 이 기능을 사용하려면 토론에 더 많이 참여해야 할 수 있습니다.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> '조회함',
	'VIEWED_COUNTS'		=> array(
		0	=> '아직 보지 않음',
		1	=> '%d번 조회',
		2	=> '%d번 조회',
	),
	'VIEWING_CONTACT_ADMIN'		=> '연락처 페이지 보는 중',
	'VIEWING_FAQ'				=> 'FAQ 보는 중',
	'VIEWING_MEMBERS'			=> '회원 세부정보 보는 중',
	'VIEWING_ONLINE'			=> '누가 온라인 상태인지 보는 중',
	'VIEWING_MCP'				=> '운영자 제어판 보는 중',
	'VIEWING_MEMBER_PROFILE'	=> '회원 프로필 보는 중',
	'VIEWING_PRIVATE_MESSAGES'	=> '비공개 메시지 보는 중',
	'VIEWING_REGISTER'			=> '계정 등록 중',
	'VIEWING_UCP'				=> '사용자 제어판 보는 중',
	'VIEWS'						=> '조회수',
	'VIEW_BOOKMARKS'			=> '북마크 보기',
	'VIEW_FORUM_LOGS'			=> '로그 보기',
	'VIEW_LATEST_POST'			=> '최신 게시물 보기',
	'VIEW_NEWEST_POST'			=> '읽지 않은 첫 번째 게시물 보기',
	'VIEW_NOTES'				=> '사용자 메모 보기',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> '최근 %d분 동안 활동한 사용자',
		2	=> '최근 %d분 동안 활동한 사용자',
	),
	'VIEW_TOPIC'				=> '글 보기',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> '공지: ',
	'VIEW_TOPIC_GLOBAL'			=> '글로벌 공지사항: ',
	'VIEW_TOPIC_LOCKED'			=> '잠김: ',
	'VIEW_TOPIC_LOGS'			=> '로그 보기',
	'VIEW_TOPIC_MOVED'			=> '이동: ',
	'VIEW_TOPIC_POLL'			=> '투표: ',
	'VIEW_TOPIC_STICKY'			=> '고정: ',
	'VISIT_WEBSITE'				=> '웹사이트 방문',

	'WARNINGS'			=> '경고',
	'WARN_USER'			=> '사용자에게 경고',
	'WATCH_FORUM_CONFIRM'	=> '이 포럼에 가입하시겠습니까?',
	'WATCH_FORUM_DETAILED'	=> '"%s" 포럼에 가입하시겠습니까?',
	'WATCH_TOPIC_CONFIRM'	=> '이 글을 구독하시겠습니까?',
	'WATCH_TOPIC_DETAILED'	=> '"%s" 글을 구독하시겠습니까?',
	'WELCOME_SUBJECT'	=> '%s 포럼에 오신 것을 환영합니다',
	'WEBSITE'			=> '웹사이트',
	'WHOIS'				=> '후이즈',
	'WHO_IS_ONLINE'		=> '접속자',
	'WRONG_PASSWORD'	=> '잘못된 비밀번호를 입력했습니다',

	'WRONG_DATA_COLOUR'			=> '입력한 색상 값이 잘못되었습니다.',
	'WRONG_DATA_JABBER'			=> '입력한 이름은 유효한 Jabber 계정 이름이 아닙니다.',
	'WRONG_DATA_LANG'			=> '지정한 언어가 유효하지 않습니다.',
	'WRONG_DATA_POST_SD'		=> '지정한 게시물 정렬 방향이 잘못되었습니다.',
	'WRONG_DATA_POST_SK'		=> '지정한 게시물 정렬 옵션이 올바르지 않습니다.',
	'WRONG_DATA_TOPIC_SD'		=> '지정한 글 정렬 방향이 올바르지 않습니다.',
	'WRONG_DATA_TOPIC_SK'		=> '지정한 글 정렬 옵션이 올바르지 않습니다.',
	'WROTE'						=> '쓴',

	'YAHOO'				=> '야후 메신저',
	'YOUTUBE'			=> '유튜브',
	'YEAR'				=> '년',
	'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
	'YES'				=> '예',
	'YOU_LAST_VISIT'	=> '마지막 방문: %s',

	'datetime'			=> array(
		'TODAY'		=> '오늘',
		'TOMORROW'	=> '내일',
		'YESTERDAY'	=> '어제',
		'AGO'		=> array(
			0		=> '1분 이내',
			1		=> '%d분 전',
			2		=> '%d분 전',
		),

		'Sunday'	=> '일요일',
		'Monday'	=> '월요일',
		'Tuesday'	=> '화요일',
		'Wednesday'	=> '수요일',
		'Thursday'	=> '목요일',
		'Friday'	=> '금요일',
		'Saturday'	=> '토요일',

		'Sun'		=> '日',
		'Mon'		=> '月',
		'Tue'		=> '火',
		'Wed'		=> '水',
		'Thu'		=> '木',
		'Fri'		=> '金',
		'Sat'		=> '土',

		'January'	=> 'January',
		'February'	=> 'February',
		'March'		=> 'March',
		'April'		=> 'April',
		'May'		=> 'May',
		'June'		=> 'June',
		'July'		=> 'July',
		'August'	=> 'August',
		'September' => 'September',
		'October'	=> 'October',
		'November'	=> 'November',
		'December'	=> 'December',

		'Jan'		=> 'Jan',
		'Feb'		=> 'Feb',
		'Mar'		=> 'Mar',
		'Apr'		=> 'Apr',
		'May_short'	=> 'May',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'Jun',
		'Jul'		=> 'Jul',
		'Aug'		=> 'Aug',
		'Sep'		=> 'Sep',
		'Oct'		=> 'Oct',
		'Nov'		=> 'Nov',
		'Dec'		=> 'Dec',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'					=> 'UTC',
		'UTC_OFFSET'			=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'		=> 'UTC+9',
		'Etc/GMT-8'		=> 'UTC+8',
		'Etc/GMT-7'		=> 'UTC+7',
		'Etc/GMT-6'		=> 'UTC+6',
		'Etc/GMT-5'		=> 'UTC+5',
		'Etc/GMT-4'		=> 'UTC+4',
		'Etc/GMT-3'		=> 'UTC+3',
		'Etc/GMT-2'		=> 'UTC+2',
		'Etc/GMT-1'		=> 'UTC+1',
		'Etc/GMT+1'		=> 'UTC-1',
		'Etc/GMT+2'		=> 'UTC-2',
		'Etc/GMT+3'		=> 'UTC-3',
		'Etc/GMT+4'		=> 'UTC-4',
		'Etc/GMT+5'		=> 'UTC-5',
		'Etc/GMT+6'		=> 'UTC-6',
		'Etc/GMT+7'		=> 'UTC-7',
		'Etc/GMT+8'		=> 'UTC-8',
		'Etc/GMT+9'		=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> 'Africa/Abidjan',
		'Africa/Accra'		=> 'Africa/Accra',
		'Africa/Addis_Ababa'	=> 'Africa/Addis Ababa',
		'Africa/Algiers'	=> 'Africa/Algiers',
		'Africa/Asmara'		=> 'Africa/Asmara',
		'Africa/Bamako'		=> 'Africa/Bamako',
		'Africa/Bangui'		=> 'Africa/Bangui',
		'Africa/Banjul'		=> 'Africa/Banjul',
		'Africa/Bissau'		=> 'Africa/Bissau',
		'Africa/Blantyre'	=> 'Africa/Blantyre',
		'Africa/Brazzaville'	=> 'Africa/Brazzaville',
		'Africa/Bujumbura'	=> 'Africa/Bujumbura',
		'Africa/Cairo'		=> 'Africa/Cairo',
		'Africa/Casablanca'	=> 'Africa/Casablanca',
		'Africa/Ceuta'		=> 'Africa/Ceuta',
		'Africa/Conakry'	=> 'Africa/Conakry',
		'Africa/Dakar'		=> 'Africa/Dakar',
		'Africa/Dar_es_Salaam'	=> 'Africa/Dar es Salaam',
		'Africa/Djibouti'	=> 'Africa/Djibouti',
		'Africa/Douala'		=> 'Africa/Douala',
		'Africa/El_Aaiun'	=> 'Africa/El Aaiun',
		'Africa/Freetown'	=> 'Africa/Freetown',
		'Africa/Gaborone'	=> 'Africa/Gaborone',
		'Africa/Harare'		=> 'Africa/Harare',
		'Africa/Johannesburg'	=> 'Africa/Johannesburg',
		'Africa/Juba'		=> 'Africa/Juba',
		'Africa/Kampala'	=> 'Africa/Kampala',
		'Africa/Khartoum'	=> 'Africa/Khartoum',
		'Africa/Kigali'		=> 'Africa/Kigali',
		'Africa/Kinshasa'	=> 'Africa/Kinshasa',
		'Africa/Lagos'		=> 'Africa/Lagos',
		'Africa/Libreville'	=> 'Africa/Libreville',
		'Africa/Lome'		=> 'Africa/Lome',
		'Africa/Luanda'		=> 'Africa/Luanda',
		'Africa/Lubumbashi'	=> 'Africa/Lubumbashi',
		'Africa/Lusaka'		=> 'Africa/Lusaka',
		'Africa/Malabo'		=> 'Africa/Malabo',
		'Africa/Maputo'		=> 'Africa/Maputo',
		'Africa/Maseru'		=> 'Africa/Maseru',
		'Africa/Mbabane'	=> 'Africa/Mbabane',
		'Africa/Mogadishu'	=> 'Africa/Mogadishu',
		'Africa/Monrovia'	=> 'Africa/Monrovia',
		'Africa/Nairobi'	=> 'Africa/Nairobi',
		'Africa/Ndjamena'	=> 'Africa/Ndjamena',
		'Africa/Niamey'		=> 'Africa/Niamey',
		'Africa/Nouakchott'	=> 'Africa/Nouakchott',
		'Africa/Ouagadougou'	=> 'Africa/Ouagadougou',
		'Africa/Porto-Novo'	=> 'Africa/Porto-Novo',
		'Africa/Sao_Tome'	=> 'Africa/Sao Tome',
		'Africa/Tripoli'	=> 'Africa/Tripoli',
		'Africa/Tunis'		=> 'Africa/Tunis',
		'Africa/Windhoek'	=> 'Africa/Windhoek',

		'America/Adak'		=> 'America/Adak',
		'America/Anchorage'	=> 'America/Anchorage',
		'America/Anguilla'	=> 'America/Anguilla',
		'America/Antigua'	=> 'America/Antigua',
		'America/Araguaina'	=> 'America/Araguaina',

		'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
		'America/Argentina/Catamarca'	=> 'America/Argentina/Catamarca',
		'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
		'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja'	=> 'America/Argentina/La Rioja',
		'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
		'America/Argentina/Salta'		=> 'America/Argentina/Salta',
		'America/Argentina/San_Juan'	=> 'America/Argentina/San Juan',
		'America/Argentina/San_Luis'	=> 'America/Argentina/San Luis',
		'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

		'America/Aruba'			=> 'America/Aruba',
		'America/Asuncion'		=> 'America/Asuncion',
		'America/Atikokan'		=> 'America/Atikokan',
		'America/Bahia'			=> 'America/Bahia',
		'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
		'America/Barbados'		=> 'America/Barbados',
		'America/Belem'			=> 'America/Belem',
		'America/Belize'		=> 'America/Belize',
		'America/Blanc-Sablon'	=> 'America/Blanc-Sablon',
		'America/Boa_Vista'		=> 'America/Boa Vista',
		'America/Bogota'		=> 'America/Bogota',
		'America/Boise'			=> 'America/Boise',
		'America/Cambridge_Bay'	=> 'America/Cambridge Bay',
		'America/Campo_Grande'	=> 'America/Campo Grande',
		'America/Cancun'		=> 'America/Cancun',
		'America/Caracas'		=> 'America/Caracas',
		'America/Cayenne'		=> 'America/Cayenne',
		'America/Cayman'		=> 'America/Cayman',
		'America/Chicago'		=> 'America/Chicago',
		'America/Chihuahua'		=> 'America/Chihuahua',
		'America/Costa_Rica'	=> 'America/Costa Rica',
		'America/Creston'		=> 'America/Creston',
		'America/Cuiaba'		=> 'America/Cuiaba',
		'America/Curacao'		=> 'America/Curacao',
		'America/Danmarkshavn'	=> 'America/Danmarkshavn',
		'America/Dawson'		=> 'America/Dawson',
		'America/Dawson_Creek'	=> 'America/Dawson Creek',
		'America/Denver'		=> 'America/Denver',
		'America/Detroit'		=> 'America/Detroit',
		'America/Dominica'		=> 'America/Dominica',
		'America/Edmonton'		=> 'America/Edmonton',
		'America/Eirunepe'		=> 'America/Eirunepe',
		'America/El_Salvador'	=> 'America/El Salvador',
		'America/Fortaleza'		=> 'America/Fortaleza',
		'America/Glace_Bay'		=> 'America/Glace Bay',
		'America/Godthab'		=> 'America/Godthab',
		'America/Goose_Bay'		=> 'America/Goose Bay',
		'America/Grand_Turk'	=> 'America/Grand Turk',
		'America/Grenada'		=> 'America/Grenada',
		'America/Guadeloupe'	=> 'America/Guadeloupe',
		'America/Guatemala'		=> 'America/Guatemala',
		'America/Guayaquil'		=> 'America/Guayaquil',
		'America/Guyana'		=> 'America/Guyana',
		'America/Halifax'		=> 'America/Halifax',
		'America/Havana'		=> 'America/Havana',
		'America/Hermosillo'		=> 'America/Hermosillo',
		'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
		'America/Indiana/Knox'		=> 'America/Indiana/Knox',
		'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
		'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
		'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
		'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
		'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
		'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
		'America/Inuvik'		=> 'America/Inuvik',
		'America/Iqaluit'		=> 'America/Iqaluit',
		'America/Jamaica'		=> 'America/Jamaica',
		'America/Juneau'		=> 'America/Juneau',
		'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
		'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
		'America/Kralendijk'	=> 'America/Kralendijk',
		'America/La_Paz'		=> 'America/La Paz',
		'America/Lima'			=> 'America/Lima',
		'America/Los_Angeles'	=> 'America/Los Angeles',
		'America/Lower_Princes'	=> 'America/Lower Princes',
		'America/Maceio'		=> 'America/Maceio',
		'America/Managua'		=> 'America/Managua',
		'America/Manaus'		=> 'America/Manaus',
		'America/Marigot'		=> 'America/Marigot',
		'America/Martinique'	=> 'America/Martinique',
		'America/Matamoros'		=> 'America/Matamoros',
		'America/Mazatlan'		=> 'America/Mazatlan',
		'America/Menominee'		=> 'America/Menominee',
		'America/Merida'		=> 'America/Merida',
		'America/Metlakatla'	=> 'America/Metlakatla',
		'America/Mexico_City'	=> 'America/Mexico City',
		'America/Miquelon'		=> 'America/Miquelon',
		'America/Moncton'		=> 'America/Moncton',
		'America/Monterrey'		=> 'America/Monterrey',
		'America/Montevideo'	=> 'America/Montevideo',
		'America/Montreal'		=> 'America/Montreal',
		'America/Montserrat'	=> 'America/Montserrat',
		'America/Nassau'		=> 'America/Nassau',
		'America/New_York'		=> 'America/New York',
		'America/Nipigon'		=> 'America/Nipigon',
		'America/Nome'			=> 'America/Nome',
		'America/Noronha'		=> 'America/Noronha',
		'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
		'America/Ojinaga'		=> 'America/Ojinaga',
		'America/Panama'		=> 'America/Panama',
		'America/Pangnirtung'	=> 'America/Pangnirtung',
		'America/Paramaribo'	=> 'America/Paramaribo',
		'America/Phoenix'		=> 'America/Phoenix',
		'America/Port-au-Prince'	=> 'America/Port-au-Prince',
		'America/Port_of_Spain'	=> 'America/Port of Spain',
		'America/Porto_Velho'	=> 'America/Porto Velho',
		'America/Puerto_Rico'	=> 'America/Puerto Rico',
		'America/Rainy_River'	=> 'America/Rainy River',
		'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
		'America/Recife'		=> 'America/Recife',
		'America/Regina'		=> 'America/Regina',
		'America/Resolute'		=> 'America/Resolute',
		'America/Rio_Branco'	=> 'America/Rio Branco',
		'America/Santa_Isabel'	=> 'America/Santa Isabel',
		'America/Santarem'		=> 'America/Santarem',
		'America/Santiago'		=> 'America/Santiago',
		'America/Santo_Domingo'	=> 'America/Santo Domingo',
		'America/Sao_Paulo'		=> 'America/Sao Paulo',
		'America/Scoresbysund'	=> 'America/Scoresbysund',
		'America/Shiprock'		=> 'America/Shiprock',
		'America/Sitka'			=> 'America/Sitka',
		'America/St_Barthelemy'	=> 'America/St. Barthelemy',
		'America/St_Johns'		=> 'America/St. Johns',
		'America/St_Kitts'		=> 'America/St. Kitts',
		'America/St_Lucia'		=> 'America/St. Lucia',
		'America/St_Thomas'		=> 'America/St. Thomas',
		'America/St_Vincent'	=> 'America/St. Vincent',
		'America/Swift_Current'	=> 'America/Swift Current',
		'America/Tegucigalpa'	=> 'America/Tegucigalpa',
		'America/Thule'			=> 'America/Thule',
		'America/Thunder_Bay'	=> 'America/Thunder Bay',
		'America/Tijuana'		=> 'America/Tijuana',
		'America/Toronto'		=> 'America/Toronto',
		'America/Tortola'		=> 'America/Tortola',
		'America/Vancouver'		=> 'America/Vancouver',
		'America/Whitehorse'	=> 'America/Whitehorse',
		'America/Winnipeg'		=> 'America/Winnipeg',
		'America/Yakutat'		=> 'America/Yakutat',
		'America/Yellowknife'	=> 'America/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'	=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'Asia/Aden'			=> 'Asia/Aden',
		'Asia/Almaty'		=> 'Asia/Almaty',
		'Asia/Amman'		=> 'Asia/Amman',
		'Asia/Anadyr'		=> 'Asia/Anadyr',
		'Asia/Aqtau'		=> 'Asia/Aqtau',
		'Asia/Aqtobe'		=> 'Asia/Aqtobe',
		'Asia/Ashgabat'		=> 'Asia/Ashgabat',
		'Asia/Baghdad'		=> 'Asia/Baghdad',
		'Asia/Bahrain'		=> 'Asia/Bahrain',
		'Asia/Baku'			=> 'Asia/Baku',
		'Asia/Bangkok'		=> 'Asia/Bangkok',
		'Asia/Beirut'		=> 'Asia/Beirut',
		'Asia/Bishkek'		=> 'Asia/Bishkek',
		'Asia/Brunei'		=> 'Asia/Brunei',
		'Asia/Choibalsan'	=> 'Asia/Choibalsan',
		'Asia/Chongqing'	=> 'Asia/Chongqing',
		'Asia/Colombo'		=> 'Asia/Colombo',
		'Asia/Damascus'		=> 'Asia/Damascus',
		'Asia/Dhaka'		=> 'Asia/Dhaka',
		'Asia/Dili'			=> 'Asia/Dili',
		'Asia/Dubai'		=> 'Asia/Dubai',
		'Asia/Dushanbe'		=> 'Asia/Dushanbe',
		'Asia/Gaza'			=> 'Asia/Gaza',
		'Asia/Harbin'		=> 'Asia/Harbin',
		'Asia/Hebron'		=> 'Asia/Hebron',
		'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
		'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
		'Asia/Hovd'			=> 'Asia/Hovd',
		'Asia/Irkutsk'		=> 'Asia/Irkutsk',
		'Asia/Jakarta'		=> 'Asia/Jakarta',
		'Asia/Jayapura'		=> 'Asia/Jayapura',
		'Asia/Jerusalem'	=> 'Asia/Jerusalem',
		'Asia/Kabul'		=> 'Asia/Kabul',
		'Asia/Kamchatka'	=> 'Asia/Kamchatka',
		'Asia/Karachi'		=> 'Asia/Karachi',
		'Asia/Kashgar'		=> 'Asia/Kashgar',
		'Asia/Kathmandu'	=> 'Asia/Kathmandu',
		'Asia/Khandyga'		=> 'Asia/Khandyga',
		'Asia/Kolkata'		=> 'Asia/Kolkata',
		'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
		'Asia/Kuching'		=> 'Asia/Kuching',
		'Asia/Kuwait'		=> 'Asia/Kuwait',
		'Asia/Macau'		=> 'Asia/Macau',
		'Asia/Magadan'		=> 'Asia/Magadan',
		'Asia/Makassar'		=> 'Asia/Makassar',
		'Asia/Manila'		=> 'Asia/Manila',
		'Asia/Muscat'		=> 'Asia/Muscat',
		'Asia/Nicosia'		=> 'Asia/Nicosia',
		'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
		'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
		'Asia/Omsk'			=> 'Asia/Omsk',
		'Asia/Oral'			=> 'Asia/Oral',
		'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
		'Asia/Pontianak'	=> 'Asia/Pontianak',
		'Asia/Pyongyang'	=> 'Asia/Pyongyang',
		'Asia/Qatar'		=> 'Asia/Qatar',
		'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
		'Asia/Rangoon'		=> 'Asia/Rangoon',
		'Asia/Riyadh'		=> 'Asia/Riyadh',
		'Asia/Sakhalin'		=> 'Asia/Sakhalin',
		'Asia/Samarkand'	=> 'Asia/Samarkand',
		'Asia/Seoul'		=> '아시아/서울',
		'Asia/Shanghai'		=> 'Asia/Shanghai',
		'Asia/Singapore'	=> 'Asia/Singapore',
		'Asia/Taipei'		=> 'Asia/Taipei',
		'Asia/Tashkent'		=> 'Asia/Tashkent',
		'Asia/Tbilisi'		=> 'Asia/Tbilisi',
		'Asia/Tehran'		=> 'Asia/Tehran',
		'Asia/Thimphu'		=> 'Asia/Thimphu',
		'Asia/Tokyo'		=> 'Asia/Tokyo',
		'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
		'Asia/Urumqi'		=> 'Asia/Urumqi',
		'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
		'Asia/Vientiane'	=> 'Asia/Vientiane',
		'Asia/Vladivostok'	=> 'Asia/Vladivostok',
		'Asia/Yakutsk'		=> 'Asia/Yakutsk',
		'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
		'Asia/Yerevan'		=> 'Asia/Yerevan',

		'Atlantic/Azores'		=> 'Atlantic/Azores',
		'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
		'Atlantic/Canary'		=> 'Atlantic/Canary',
		'Atlantic/Cape_Verde'	=> 'Atlantic/Cape Verde',
		'Atlantic/Faroe'		=> 'Atlantic/Faroe',
		'Atlantic/Madeira'		=> 'Atlantic/Madeira',
		'Atlantic/Reykjavik'	=> 'Atlantic/Reykjavik',
		'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
		'Atlantic/St_Helena'	=> 'Atlantic/St. Helena',
		'Atlantic/Stanley'		=> 'Atlantic/Stanley',

		'Australia/Adelaide'	=> 'Australia/Adelaide',
		'Australia/Brisbane'	=> 'Australia/Brisbane',
		'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
		'Australia/Currie'		=> 'Australia/Currie',
		'Australia/Darwin'		=> 'Australia/Darwin',
		'Australia/Eucla'		=> 'Australia/Eucla',
		'Australia/Hobart'		=> 'Australia/Hobart',
		'Australia/Lindeman'	=> 'Australia/Lindeman',
		'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
		'Australia/Melbourne'	=> 'Australia/Melbourne',
		'Australia/Perth'		=> 'Australia/Perth',
		'Australia/Sydney'		=> 'Australia/Sydney',

		'Europe/Amsterdam'	=> 'Europe/Amsterdam',
		'Europe/Andorra'	=> 'Europe/Andorra',
		'Europe/Athens'		=> 'Europe/Athens',
		'Europe/Belgrade'	=> 'Europe/Belgrade',
		'Europe/Berlin'		=> 'Europe/Berlin',
		'Europe/Bratislava'	=> 'Europe/Bratislava',
		'Europe/Brussels'	=> 'Europe/Brussels',
		'Europe/Bucharest'	=> 'Europe/Bucharest',
		'Europe/Budapest'	=> 'Europe/Budapest',
		'Europe/Busingen'	=> 'Europe/Busingen',
		'Europe/Chisinau'	=> 'Europe/Chisinau',
		'Europe/Copenhagen'	=> 'Europe/Copenhagen',
		'Europe/Dublin'		=> 'Europe/Dublin',
		'Europe/Gibraltar'	=> 'Europe/Gibraltar',
		'Europe/Guernsey'	=> 'Europe/Guernsey',
		'Europe/Helsinki'	=> 'Europe/Helsinki',
		'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
		'Europe/Istanbul'	=> 'Europe/Istanbul',
		'Europe/Jersey'		=> 'Europe/Jersey',
		'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
		'Europe/Kiev'		=> 'Europe/Kiev',
		'Europe/Lisbon'		=> 'Europe/Lisbon',
		'Europe/Ljubljana'	=> 'Europe/Ljubljana',
		'Europe/London'		=> 'Europe/London',
		'Europe/Luxembourg'	=> 'Europe/Luxembourg',
		'Europe/Madrid'		=> 'Europe/Madrid',
		'Europe/Malta'		=> 'Europe/Malta',
		'Europe/Mariehamn'	=> 'Europe/Mariehamn',
		'Europe/Minsk'		=> 'Europe/Minsk',
		'Europe/Monaco'		=> 'Europe/Monaco',
		'Europe/Moscow'		=> 'Europe/Moscow',
		'Europe/Oslo'		=> 'Europe/Oslo',
		'Europe/Paris'		=> 'Europe/Paris',
		'Europe/Podgorica'	=> 'Europe/Podgorica',
		'Europe/Prague'		=> 'Europe/Prague',
		'Europe/Riga'		=> 'Europe/Riga',
		'Europe/Rome'		=> 'Europe/Rome',
		'Europe/Samara'		=> 'Europe/Samara',
		'Europe/San_Marino'	=> 'Europe/San Marino',
		'Europe/Sarajevo'	=> 'Europe/Sarajevo',
		'Europe/Simferopol'	=> 'Europe/Simferopol',
		'Europe/Skopje'		=> 'Europe/Skopje',
		'Europe/Sofia'		=> 'Europe/Sofia',
		'Europe/Stockholm'	=> 'Europe/Stockholm',
		'Europe/Tallinn'	=> 'Europe/Tallinn',
		'Europe/Tirane'		=> 'Europe/Tirane',
		'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
		'Europe/Vaduz'		=> 'Europe/Vaduz',
		'Europe/Vatican'	=> 'Europe/Vatican',
		'Europe/Vienna'		=> 'Europe/Vienna',
		'Europe/Vilnius'	=> 'Europe/Vilnius',
		'Europe/Volgograd'	=> 'Europe/Volgograd',
		'Europe/Warsaw'		=> 'Europe/Warsaw',
		'Europe/Zagreb'		=> 'Europe/Zagreb',
		'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
		'Europe/Zurich'		=> 'Europe/Zurich',

		'Indian/Antananarivo'	=> 'Indian/Antananarivo',
		'Indian/Chagos'		=> 'Indian/Chagos',
		'Indian/Christmas'	=> 'Indian/Christmas',
		'Indian/Cocos'		=> 'Indian/Cocos',
		'Indian/Comoro'		=> 'Indian/Comoro',
		'Indian/Kerguelen'	=> 'Indian/Kerguelen',
		'Indian/Mahe'		=> 'Indian/Mahe',
		'Indian/Maldives'	=> 'Indian/Maldives',
		'Indian/Mauritius'	=> 'Indian/Mauritius',
		'Indian/Mayotte'	=> 'Indian/Mayotte',
		'Indian/Reunion'	=> 'Indian/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// 값은 예시일 뿐이며 현재 표시되는 시간으로 대체됩니다.
	// 참고 https://www.php.net/manual/en/datetime.format.php
	'dateformats'	=> array(
		'Y-m-d H:i'			=> '2007-01-01 13:37',
		'Y-m-d l H:i'		=> '2007-01-01 월요일 13:37',
		'Y-m-d D h:i A'		=> '2007-01-01 月 01:37 PM',
	),

	// 이 언어로 새로 설치할 때 사용할 기본 날짜 형식
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'Y-m-d l H:i'  // 2007-01-01 월요일 13:37

));
