<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

$lang = array_merge($lang, array(
	'ACTION'				=> '적용',
	'ACTION_NOTE'			=> '정용/메모',
	'ADD_FEEDBACK'			=> '피드백 추가',
	'ADD_FEEDBACK_EXPLAIN'	=> '이에 대한 보고서를 추가하려면 다음 양식을 작성하십시오. 일반 텍스트만 사용하십시오. HTML, BBCode 등은 허용되지 않습니다.',
	'ADD_WARNING'			=> '경고 추가',
	'ADD_WARNING_EXPLAIN'	=> '이 사용자에게 경고를 보내려면 다음 양식을 작성하십시오. 일반 텍스트만 사용하십시오. HTML, BBCode 등은 허용되지 않습니다.',
	'ALL_ENTRIES'			=> '모든 항목',
	'ALL_NOTES_DELETED'		=> '모든 사용자 메모를 성공적으로 제거했습니다.',
	'ALL_REPORTS'			=> '모든 보고서',
	'ALREADY_REPORTED'		=> '이미 신고된 게시물입니다.',
	'ALREADY_REPORTED_PM'	=> '이 비공개 메시지는 이미 보고되었습니다.',
	'ALREADY_WARNED'		=> '이 게시물에 대한 경고가 이미 발행되었습니다.',
	'APPROVE'				=> '승인하다',
	'APPROVE_POST'			=> '게시물 승인',
	'APPROVE_POST_CONFIRM'	=> '이 게시물을 승인하시겠습니까?',
	'APPROVE_POSTS'			=> '게시물 승인',
	'APPROVE_POSTS_CONFIRM'	=> '선택한 게시물을 승인하시겠습니까?',
	'APPROVE_TOPIC'			=> '글 승인',
	'APPROVE_TOPIC_CONFIRM'	=> '이 글을 승인하시겠습니까?',
	'APPROVE_TOPICS'		=> '글 승인',
	'APPROVE_TOPICS_CONFIRM'=> '선택한 글을 승인하시겠습니까?',

	'CANNOT_MOVE_SAME_FORUM'=> '이미 있는 포럼으로 글를 이동할 수 없습니다.',
	'CANNOT_WARN_ANONYMOUS'	=> '등록되지 않은 게스트 사용자에게 경고할 수 없습니다.',
	'CANNOT_WARN_SELF'		=> '스스로 경고할 수 없습니다.',
	'CAN_LEAVE_BLANK'		=> '공백으로 둘 수 있습니다.',
	'CHANGE_POSTER'			=> '게시자 변경',
	'CLOSE_PM_REPORT'		=> 'PM 보고서 닫기',
	'CLOSE_PM_REPORT_CONFIRM'	=> '선택한 PM 보고서를 닫으시겠습니까?',
	'CLOSE_PM_REPORTS'		=> 'PM 보고서 닫기',
	'CLOSE_PM_REPORTS_CONFIRM'	=> '선택한 PM 보고서를 닫으시겠습니까?',
	'CLOSE_REPORT'			=> '보고서 닫기',
	'CLOSE_REPORT_CONFIRM'	=> '선택한 보고서를 닫으시겠습니까?',
	'CLOSE_REPORTS'			=> '보고서 닫기',
	'CLOSE_REPORTS_CONFIRM'	=> '선택한 보고서를 닫으시겠습니까?',

	'DELETE_PM_REPORT'			=> 'PM 보고서 삭제',
	'DELETE_PM_REPORT_CONFIRM'	=> '선택한 PM 보고서를 삭제하시겠습니까?',
	'DELETE_PM_REPORTS'			=> 'PM 보고서 삭제',
	'DELETE_PM_REPORTS_CONFIRM'	=> '선택한 PM 보고서를 삭제하시겠습니까?',
	'DELETE_POSTS'				=> '게시물 삭제',
	'DELETE_REPORT'				=> '보고서 삭제',
	'DELETE_REPORT_CONFIRM'		=> '선택한 보고서를 삭제하시겠습니까?',
	'DELETE_REPORTS'			=> '보고서 삭제',
	'DELETE_REPORTS_CONFIRM'	=> '선택한 보고서를 삭제하시겠습니까?',
	'DELETE_SHADOW_TOPIC'		=> '그림자 글 삭제',
	'DELETE_TOPICS'				=> '선택한 글 삭제',
	'DISAPPROVE'				=> '비승인',
	'DISAPPROVE_REASON'			=> '비승인 사유',
	'DISAPPROVE_POST'			=> '게시물 비승인',
	'DISAPPROVE_POST_CONFIRM'	=> '이 게시물을 승인하지 않으시겠습니까?',
	'DISAPPROVE_POSTS'			=> '게시물 비승인',
	'DISAPPROVE_POSTS_CONFIRM'	=> '선택한 게시물을 승인하지 않으시겠습니까?',
	'DISPLAY_LOG'				=> '이전 항목 보기',
	'DISPLAY_OPTIONS'			=> '디스플레이 옵션',

	'EMPTY_REPORT'					=> '이 사유를 선택할 때 설명을 입력해야 합니다.',
	'EMPTY_TOPICS_REMOVED_WARNING'	=> '하나 또는 여러 개의 글이 비어 있거나 비어 있기 때문에 데이터베이스에서 제거되었습니다.',

	'FEEDBACK'				=> '피드백',
	'FORK'					=> '복사',
	'FORK_TOPIC'			=> '글복사',
	'FORK_TOPIC_CONFIRM'	=> '이 글을 복사하시겠습니까?',
	'FORK_TOPICS'			=> '선택한 글 복사',
	'FORK_TOPICS_CONFIRM'	=> '선택한 글을 복사하시겠습니까?',
	'FORUM_DESC'			=> '설명',
	'FORUM_NAME'			=> '포럼 이름',
	'FORUM_NOT_EXIST'		=> '선택한 포럼이 존재하지 않습니다.',
	'FORUM_NOT_POSTABLE'	=> '선택한 포럼을 게시할 수 없습니다.',
	'FORUM_STATUS'			=> '포럼 상태',
	'FORUM_STYLE'			=> '포럼 스타일',

	'GLOBAL_ANNOUNCEMENT'	=> '글로벌 공지',

	'IP_INFO'				=> 'IP 주소 정보',
	'IPS_POSTED_FROM'		=> '이 사용자가 게시한 IP 주소',

	'LATEST_LOGS'				=> '최근 5개의 기록된 작업',
	'LATEST_REPORTED'			=> '최근 5개의 보고서',
	'LATEST_REPORTED_PMS'		=> '최근 PM 5개의 보고서',
	'LATEST_UNAPPROVED'			=> '승인 대기 중인 최신 게시물 5개',
	'LATEST_WARNING_TIME'		=> '최근 경고 발생 이슈',
	'LATEST_WARNINGS'			=> '최근 5개의 경고',
	'LEAVE_SHADOW'				=> '섀도우 항목을 그대로 둡니다.',
	'LIST_REPORTS'				=> array(
		1	=> '%d 보고서',
		2	=> '%d 보고서',
	),
	'LOCK'						=> '잠금',
	'LOCK_POST_POST'			=> '게시물 잠금',
	'LOCK_POST_POST_CONFIRM'	=> '선택한 게시물 잠금 게시물을 편집하지 못하게 하시겠습니까?',
	'LOCK_POST_POSTS'			=> '선택한 게시물 잠금',
	'LOCK_POST_POSTS_CONFIRM'	=> '선택한 게시물을 수정하지 못하게 하시겠습니까?',
	'LOCK_TOPIC_CONFIRM'		=> '이 글을 잠그시겠습니까?',
	'LOCK_TOPICS'				=> '선택한 글 잠금',
	'LOCK_TOPICS_CONFIRM'		=> '선택한 모든 글을 잠그시겠습니까?',
	'LOGS_CURRENT_TOPIC'		=> '현재 보고 있는 로그:',
	'LOGIN_EXPLAIN_MCP'			=> '이 포럼을 중재하려면 로그인해야 합니다.',
	'LOGVIEW_VIEWPOST'			=> '게시물 보기',
	'LOGVIEW_VIEWTOPIC'			=> '글 보기',
	'LOGVIEW_VIEWLOGS'			=> '글 로그 보기',
	'LOGVIEW_VIEWFORUM'			=> '포럼 보기',
	'LOOKUP_ALL'				=> '모든 IP 조회',
	'LOOKUP_IP'					=> 'IP 조회',

	'MARKED_NOTES_DELETED'		=> '표시된 모든 사용자 메모를  제거했습니다.',

	'MCP_ADD'						=> '경고 추가',

	'MCP_BAN'					=> '차단',
	'MCP_BAN_EMAILS'			=> '이메일 차단',
	'MCP_BAN_IPS'				=> 'IP 차단',
	'MCP_BAN_USERNAMES'			=> '사용자 이름 차단',

	'MCP_LOGS'						=> '운영자 로그',
	'MCP_LOGS_FRONT'				=> '첫 페이지',
	'MCP_LOGS_FORUM_VIEW'			=> '포럼 로그',
	'MCP_LOGS_TOPIC_VIEW'			=> '글 로그',

	'MCP_MAIN'						=> '매인',
	'MCP_MAIN_FORUM_VIEW'			=> '포럼 보기',
	'MCP_MAIN_FRONT'				=> '첫 페이지',
	'MCP_MAIN_POST_DETAILS'			=> '게시물 세부정보',
	'MCP_MAIN_TOPIC_VIEW'			=> '글 보기',
	'MCP_MAKE_ANNOUNCEMENT'			=> '"공지"로 수정',
	'MCP_MAKE_ANNOUNCEMENT_CONFIRM'	=> '이 글을 "공지"로 변경하시겠습니까?',
	'MCP_MAKE_ANNOUNCEMENTS'		=> '"공지사항"으로 수정',
	'MCP_MAKE_ANNOUNCEMENTS_CONFIRM'=> '선택한 글을 "공지사항"으로 변경하시겠습니까?',
	'MCP_MAKE_GLOBAL'				=> '"글로벌 공지"로 수정',
	'MCP_MAKE_GLOBAL_CONFIRM'		=> '이 글을 "글로벌 발표"로 변경하시겠습니까?',
	'MCP_MAKE_GLOBALS'				=> '"글로벌 공지사항"으로 수정',
	'MCP_MAKE_GLOBALS_CONFIRM'		=> '선택한 글을 "글로벌 공지사항"으로 변경하시겠습니까?',
	'MCP_MAKE_STICKY'				=> '"고정"으로 수정',
	'MCP_MAKE_STICKY_CONFIRM'		=> '이 글을 "고정"으로 변경하시겠습니까?',
	'MCP_MAKE_STICKIES'				=> '"고정"으로 수정',
	'MCP_MAKE_STICKIES_CONFIRM'		=> '선택한 글을 "고정"로 변경하시겠습니까?',
	'MCP_MAKE_NORMAL'				=> '"표준 글"로 수정',
	'MCP_MAKE_NORMAL_CONFIRM'		=> '이 글을 "표준 글"로 변경하시겠습니까?',
	'MCP_MAKE_NORMALS'				=> '"표준 글"로 수정',
	'MCP_MAKE_NORMALS_CONFIRM'		=> '선택한 글을 "표준 글"로 변경하시겠습니까?',

	'MCP_NOTES'						=> '사용자 메모',
	'MCP_NOTES_FRONT'				=> '첫 페이지',
	'MCP_NOTES_USER'				=> '사용자 세부정보',

	'MCP_POST_REPORTS'				=> '이 게시물에 발행된 이슈 보고서',

	'MCP_PM_REPORTS'				=> '보고된 PM',
	'MCP_PM_REPORT_DETAILS'			=> 'PM 보고서 세부정보',
	'MCP_PM_REPORTS_CLOSED'			=> '마감된 PM 보고서',
	'MCP_PM_REPORTS_CLOSED_EXPLAIN'	=> '이것은 이전에 해결된 비공개 메시지에 대한 모든 보고서 목록입니다.',
	'MCP_PM_REPORTS_OPEN'			=> 'PM 보고서 열기',
	'MCP_PM_REPORTS_OPEN_EXPLAIN'	=> '아직 처리해야 하는 보고된 모든 비공개 메시지의 목록입니다.',

	'MCP_REPORTS'					=> '보고된 메시지',
	'MCP_REPORT_DETAILS'			=> '보고서 세부정보',
	'MCP_REPORTS_CLOSED'			=> '마감된 보고서',
	'MCP_REPORTS_CLOSED_EXPLAIN'	=> '이전에 해결된 게시물에 대한 모든 보고서 목록입니다.',
	'MCP_REPORTS_OPEN'				=> '보고서 열기',
	'MCP_REPORTS_OPEN_EXPLAIN'		=> '아직 처리되지 않은 보고된 모든 게시물의 목록입니다.',

	'MCP_QUEUE'								=> '승인 대기열',
	'MCP_QUEUE_APPROVE_DETAILS'				=> '세부정보 승인',
	'MCP_QUEUE_UNAPPROVED_POSTS'			=> '승인 대기 중인 게시물',
	'MCP_QUEUE_UNAPPROVED_POSTS_EXPLAIN'	=> '이것은 사용자에게 표시되기 전에 승인이 필요한 모든 게시물의 목록입니다.',
	'MCP_QUEUE_UNAPPROVED_TOPICS'			=> '승인 대기 중인 글',
	'MCP_QUEUE_UNAPPROVED_TOPICS_EXPLAIN'	=> '이것은 사용자에게 표시되기 전에 승인이 필요한 모든 글을 목록입니다.',
	'MCP_QUEUE_DELETED_POSTS'				=> '삭제된 게시물',
	'MCP_QUEUE_DELETED_POSTS_EXPLAIN'		=> '일시 삭제된 모든 게시물의 목록입니다. 이 화면에서 게시물을 복원하거나 영구적으로 삭제할 수 있습니다.',
	'MCP_QUEUE_DELETED_TOPICS'				=> '삭제된 글',
	'MCP_QUEUE_DELETED_TOPICS_EXPLAIN'		=> '이것은 일시 삭제된 모든 글을 목록입니다. 이 화면에서 글을 복원하거나 영구적으로 삭제할 수 있습니다.',

	'MCP_VIEW_USER'			=> '특정 사용자에 대한 경고 보기',

	'MCP_WARN'				=> '경고',
	'MCP_WARN_FRONT'		=> '첫 페이지',
	'MCP_WARN_LIST'			=> '경고 표시',
	'MCP_WARN_POST'			=> '특정 게시물에 대해 경고',
	'MCP_WARN_USER'			=> '사용자에게 경고',

	'MERGE_POSTS_CONFIRM'	=> '선택한 게시물을 이동하시겠습니까?',
	'MERGE_TOPIC_EXPLAIN'	=> '아래 양식을 사용하여 선택한 게시물을 다른 글로 이동할 수 있습니다. 게시물이 이 글에서 분리되어 다른 글에 병합됩니다. 이 게시물은 재정렬되지 않고 사용자가 새글에 게시한 것처럼 나타납니다.<br />대상 글 ID를 입력하거나 "글 선택"을 클릭하여 검색하십시오.',
	'MERGE_TOPIC_ID'		=> '대상 글 식별 번호',
	'MERGE_TOPICS'			=> '글 합치기',
	'MERGE_TOPICS_CONFIRM'	=> '선택한 글을 합치시겠습니까?',
	'MODERATE_FORUM'		=> '포럼 중재',
	'MODERATE_TOPIC'		=> '적당한 글',
	'MODERATE_POST'			=> '게시물 검토',
	'MOD_OPTIONS'			=> '운영자 옵션',
	'MORE_INFO'				=> '추가 정보',
	'MOST_WARNINGS'			=> '경고가 가장 많은 사용자',
	'MOVE_TOPIC_CONFIRM'	=> '글을 새 포럼으로 옮기시겠습니까?',
	'MOVE_TOPICS'			=> '선택한 글 이동',
	'MOVE_TOPICS_CONFIRM'	=> '선택한 글을 새 포럼으로 이동하시겠습니까?',

	'NOTIFY_POSTER_APPROVAL'		=> '작성자에게 승인을 알리시겠습니까?',
	'NOTIFY_POSTER_DISAPPROVAL'		=> '작성자에게 비승인 사실을 알리시겠습니까?',
	'NOTIFY_USER_WARN'				=> '사용자에게 경고를 알리시겠습니까?',
	'NOT_MODERATOR'					=> '당신은 이 포럼의 운영자가 아닙니다.',
	'NO_DESTINATION_FORUM'			=> '대상 포럼을 선택하십시오.',
	'NO_DESTINATION_FORUM_FOUND'	=> '사용할 수 있는 대상 포럼이 없습니다.',
	'NO_ENTRIES'					=> '로그 항목이 없습니다.',
	'NO_FEEDBACK'					=> '이 사용자에 대한 피드백이 없습니다.',
	'NO_FINAL_TOPIC_SELECTED'		=> '게시물을 병합할 대상 글을 선택해야 합니다.',
	'NO_MATCHES_FOUND'				=> '검색 결과가 없습니다.',
	'NO_POST'						=> '게시물에 대해 사용자에게 경고하려면 게시물을 선택해야 합니다.',
	'NO_POST_REPORT'				=> '신고되지 않은 게시물입니다.',
	'NO_POST_SELECTED'				=> '이 작업을 수행하려면 게시물을 하나 이상 선택해야 합니다.',
	'NO_POSTS_DELETED'				=> '삭제된 글이 없습니다.',
	'NO_POSTS_QUEUE'				=> '승인 대기 중인 게시물이 없습니다.',
	'NO_REASON_DISAPPROVAL'			=> '비승인 사유를 적절하게 기재해 주십시오.',
	'NO_REPORT'						=> '보고서를 찾을 수 없습니다.',
	'NO_REPORTS'					=> '보고서를 찾을 수 없습니다.',
	'NO_REPORT_SELECTED'			=> '이 작업을 수행하려면 보고서를 하나 이상 선택해야 합니다.',
	'NO_TOPIC_ICON'					=> '없음',
	'NO_TOPIC_SELECTED'				=> '이 작업을 수행하려면 하나 이상의 글을 선택해야 합니다.',
	'NO_TOPICS_DELETED'				=> '삭제된 글이 없습니다.',
	'NO_TOPICS_QUEUE'				=> '승인 대기 중인 글이 없습니다.',

	'ONLY_TOPIC'			=> '오로지 글 "%s"만',
	'OTHER_USERS'			=> '이 IP에서 게시하는 다른 사용자',

	'QUICKMOD_ACTION_NOT_ALLOWED' => "%s은(는) 빠른 모드로 허용되지 않습니다.",

	'PM_REPORT_CLOSED_SUCCESS'	=> '선택한 PM 보고서가 성공적으로 마감되었습니다.',
	'PM_REPORT_DELETED_SUCCESS'	=> '선택한 PM 보고서가 성공적으로 삭제되었습니다.',
	'PM_REPORTED_SUCCESS'		=> '이 비공개 메시지는 성공적으로 보고되었습니다.',
	'PM_REPORTS_CLOSED_SUCCESS'	=> '선택한 PM 보고서가 성공적으로 마감되었습니다.',
	'PM_REPORTS_DELETED_SUCCESS'=> '선택한 PM 보고서가 성공적으로 삭제되었습니다.',
	'PM_REPORTS_TOTAL'			=> array(
		0	=> '검토할 PM 보고서가 없습니다',
		1	=> '총 검토할 PM 보고서가 <strong>1</strong>개 있습니다.',
		2	=> '총 검토할 PM 보고서가 <strong>%d</strong>개 있습니다.',
	),
	'PM_REPORT_DETAILS'			=> '비공개 메시지 보고서 세부정보',
	'POSTER'					=> '게시자',
	'POSTS_APPROVED_SUCCESS'	=> '선택한 게시물이 승인되었습니다.',
	'POSTS_DELETED_SUCCESS'		=> '선택한 게시물이 데이터베이스에서 성공적으로 제거되었습니다.',
	'POSTS_DISAPPROVED_SUCCESS'	=> '선택한 게시물이 승인되지 않았습니다.',
	'POSTS_LOCKED_SUCCESS'		=> '선택한 게시물이 성공적으로 잠겼습니다.',
	'POSTS_MERGED_SUCCESS'		=> '선택한 게시물이 병합되었습니다.',
	'POSTS_PER_PAGE'			=> '페이지당 게시물',
	'POSTS_PER_PAGE_EXPLAIN'	=> '(0으로 설정하면 모든 게시물을 볼 수 있습니다.)',
	'POSTS_RESTORED_SUCCESS'	=> '선택한 게시물이 복원되었습니다.',
	'POSTS_UNLOCKED_SUCCESS'	=> '선택한 게시물의 잠금이 해제되었습니다.',
	'POST_APPROVED_SUCCESS'		=> '선택한 게시물이 승인되었습니다.',
	'POST_DELETED_SUCCESS'		=> '선택한 게시물이 데이터베이스에서 성공적으로 제거되었습니다.',
	'POST_DISAPPROVED_SUCCESS'	=> '선택한 게시물이 승인되지 않았습니다.',
	'POST_LOCKED_SUCCESS'		=> '게시물이 성공적으로 잠겼습니다.',
	'POST_NOT_EXIST'			=> '요청하신 게시물이 존재하지 않습니다.',
	'POST_REPORTED_SUCCESS'		=> '이 게시물은 성공적으로 신고되었습니다.',
	'POST_RESTORED_SUCCESS'		=> '이 게시물은 성공적으로 복원되었습니다.',
	'POST_UNLOCKED_SUCCESS'		=> '게시물 잠금이 성공적으로 해제되었습니다.',

	'READ_USERNOTES'			=> '사용자 메모',
	'READ_WARNINGS'				=> '사용자 경고',
	'REPORTER'					=> '보고자',
	'REPORTED'					=> '보고됨',
	'REPORTED_BY'				=> '신고자',
	'REPORTED_ON_DATE'			=> '온(on)',
	'REPORTS_CLOSED_SUCCESS'	=> '선택한 보고서가 성공적으로 닫혔습니다.',
	'REPORTS_DELETED_SUCCESS'	=> '선택한 보고서가 성공적으로 삭제되었습니다.',
	'REPORTS_TOTAL'				=> array(
		0	=> '검토할 보고서가 없습니다.',
		1	=> '검토할 보고서가 총 <strong>1</strong>개 있습니다.',
		2	=> '검토할 보고서가 총 <strong>%d</strong>개 있습니다.',
	),
	'REPORT_CLOSED'				=> '이 보고서는 이미 닫혔습니다.',
	'REPORT_CLOSED_SUCCESS'		=> '선택한 보고서가 성공적으로 마감되었습니다.',
	'REPORT_DELETED_SUCCESS'	=> '선택한 보고서가 성공적으로 삭제되었습니다.',
	'REPORT_DETAILS'			=> '보고서 세부정보',
	'REPORT_MESSAGE'			=> '이 메시지 신고',
	'REPORT_MESSAGE_EXPLAIN'	=> '이 양식을 사용하여 선택한 비공개 메시지를 신고하세요. 보고는 일반적으로 메시지가 포럼 규칙을 위반하는 경우에만 사용해야 합니다. <strong>비공개 메시지를 신고하면 모든 운영자가 그 내용을 볼 수 있습니다.</strong>',
	'REPORT_NOTIFY'				=> '나를 통지',
	'REPORT_NOTIFY_EXPLAIN'		=> '신고가 처리되면 알려줍니다.',
	'REPORT_POST_EXPLAIN'		=> '이 양식을 사용하여 선택한 게시물을 포럼 운영자와 보드 관리자에게 보고합니다. 보고는 일반적으로 게시물이 포럼 규칙을 위반하는 경우에만 사용해야 합니다.',
	'REPORT_REASON'				=> '신고 사유',
	'REPORT_TIME'				=> '보고 시간',
	'RESTORE'					=> '복원',
	'RESTORE_POST'				=> '게시물 복원',
	'RESTORE_POST_CONFIRM'		=> '이 게시물을 복원하시겠습니까?',
	'RESTORE_POSTS'				=> '게시물 복원',
	'RESTORE_POSTS_CONFIRM'		=> '선택한 게시물을 복원하시겠습니까?',
	'RESTORE_TOPIC'				=> '글 복원',
	'RESTORE_TOPIC_CONFIRM'		=> '이 글을 복원하시겠습니까?',
	'RESTORE_TOPICS'			=> '글 복원',
	'RESTORE_TOPICS_CONFIRM'	=> '선택한 글을 복원하시겠습니까?',
	'RESYNC'					=> '재동기화',
	'RETURN_MESSAGE'			=> '%메시지로 돌아가기%s',
	'RETURN_NEW_FORUM'			=> '%s새 포럼으로 이동%s',
	'RETURN_NEW_TOPIC'			=> '%s새글로 이동%s',
	'RETURN_PM'					=> '%s비공개 메시지로 돌아가기%s',
	'RETURN_POST'				=> '%s게시물로 돌아가기%s',
	'RETURN_QUEUE'				=> '%s대기열로 돌아가기%s',
	'RETURN_REPORTS'			=> '보고서로 돌아가기',
	'RETURN_TOPIC_SIMPLE'		=> '%s글로 돌아가기%s',

	'SEARCH_POSTS_BY_USER'				=> '게시물 검색',
	'SELECT_ACTION'						=> '원하는 작업 선택',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENT'	=> '이 글로벌 발표를 표시할 포럼을 선택하십시오.',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENTS'	=> '선택한 글 중 하나 이상이 글로벌 발표입니다. 표시할 포럼을 선택하십시오.',
	'SELECT_MERGE'						=> '선택해서 글 합치기',
	'SELECT_TOPICS_FROM'				=> '다음에서 글 선택',
	'SELECT_TOPIC'						=> '글 선택',
	'SELECT_USER'						=> '사용자 선택',
	'SORT_ACTION'						=> '로그 작업',
	'SORT_DATE'							=> '날짜',
	'SORT_IP'							=> 'IP 어드레스',
	'SORT_WARNINGS'						=> '경고',
	'SPLIT_AFTER'						=> '선택한 게시물부터 글 분할',
	'SPLIT_FORUM'						=> '새글에 대한 포럼',
	'SPLIT_POSTS'						=> '선택한 게시물 분할',
	'SPLIT_SUBJECT'						=> '새글 제목',
	'SPLIT_TOPIC_ALL'					=> '선택한 게시물에서 글 분할',
	'SPLIT_TOPIC_ALL_CONFIRM'			=> '이 글을 나누시겠습니까?',
	'SPLIT_TOPIC_BEYOND'				=> '선택한 게시물에서 글 분할',
	'SPLIT_TOPIC_BEYOND_CONFIRM'		=> '선택한 게시물에서 이 글을 나누시겠습니까?',
	'SPLIT_TOPIC_EXPLAIN'				=> '아래 양식을 사용하여 게시물을 개별적으로 선택하거나 선택한 게시물에서 분할하여 글을 둘로 나눌 수 있습니다.',

	'THIS_PM_IP'				=> '이 비공개 메시지의 IP',
	'THIS_POST_IP'				=> '이 게시물의 IP',
	'TOPICS_APPROVED_SUCCESS'	=> '선택한 글이 승인되었습니다.',
	'TOPICS_DELETED_SUCCESS'	=> '선택한 글이 데이터베이스에서 성공적으로 제거되었습니다.',
	'TOPICS_DISAPPROVED_SUCCESS'=> '선택한 글이 비승인되었습니다.',
	'TOPICS_FORKED_SUCCESS'		=> '선택한 글이 성공적으로 복사되었습니다.',
	'TOPICS_LOCKED_SUCCESS'		=> '선택한 글이 잠겨 있습니다.',
	'TOPICS_MOVED_SUCCESS'		=> '선택한 글이 성공적으로 이동되었습니다.',
	'TOPICS_RESTORED_SUCCESS'	=> '선택한 글이 성공적으로 복원되었습니다.',
	'TOPICS_RESYNC_SUCCESS'		=> '선택한 글이 다시 동기화되었습니다.',
	'TOPICS_TYPE_CHANGED'		=> '글 유형이 성공적으로 변경되었습니다.',
	'TOPICS_UNLOCKED_SUCCESS'	=> '선택한 글이 잠금 해제되었습니다.',
	'TOPIC_APPROVED_SUCCESS'	=> '선택한 글이 승인되었습니다.',
	'TOPIC_DELETED_SUCCESS'		=> '선택한 글이 데이터베이스에서 성공적으로 제거되었습니다.',
	'TOPIC_DISAPPROVED_SUCCESS'	=> '선택한 글이 승인되지 않았습니다.',
	'TOPIC_FORKED_SUCCESS'		=> '선택한 글이 성공적으로 복사되었습니다.',
	'TOPIC_LOCKED_SUCCESS'		=> '선택한 글이 잠겨 있습니다.',
	'TOPIC_MOVED_SUCCESS'		=> '선택한 글이 성공적으로 이동되었습니다.',
	'TOPIC_NOT_EXIST'			=> '선택한 글이 존재하지 않습니다.',
	'TOPIC_RESTORED_SUCCESS'	=> '선택한 글이 성공적으로 복원되었습니다.',
	'TOPIC_RESYNC_SUCCESS'		=> '선택한 글이 다시 동기화되었습니다.',
	'TOPIC_SPLIT_SUCCESS'		=> '선택한 글이 성공적으로 분할되었습니다.',
	'TOPIC_TIME'				=> '글 시간',
	'TOPIC_TYPE_CHANGED'		=> '글 유형이 성공적으로 변경되었습니다.',
	'TOPIC_UNLOCKED_SUCCESS'	=> '선택한 글이 잠금 해제되었습니다.',
	'TOTAL_WARNINGS'			=> '총 경고',

	'UNAPPROVED_POSTS_TOTAL'		=> array(
		0	=> '승인 대기 중인 게시물이 없습니다',
		1	=> '총 <strong>1</strong>개의 게시물이 승인 대기 중입니다.',
		2	=> '총 <strong>%d</strong>개의 게시물이 승인 대기 중입니다.',
	),
	'UNLOCK'						=> '잠금해제',
	'UNLOCK_POST'					=> '게시물 잠금 해제',
	'UNLOCK_POST_EXPLAIN'			=> '수정 허용',
	'UNLOCK_POST_POST'				=> '게시물 잠금 해제',
	'UNLOCK_POST_POST_CONFIRM'		=> '이 게시물의 수정을 허용하시겠습니까?',
	'UNLOCK_POST_POSTS'				=> '선택된 게시물 잠금 해제',
	'UNLOCK_POST_POSTS_CONFIRM'		=> '선택한 게시물의 수정을 허용하시겠습니까?',
	'UNLOCK_TOPIC'					=> '글 잠금 해제',
	'UNLOCK_TOPIC_CONFIRM'			=> '이 글을 잠금을 해제하시겠습니까?',
	'UNLOCK_TOPICS'					=> '선택된 글 잠금 해제',
	'UNLOCK_TOPICS_CONFIRM'			=> '선택한 모든 글을 잠금을 해제하시겠습니까?',
	'USER_CANNOT_POST'				=> '이 포럼에는 게시할 수 없습니다.',
	'USER_CANNOT_REPORT'			=> '이 포럼에서는 게시물을 신고할 수 없습니다.',
	'USER_FEEDBACK_ADDED'			=> '사용자 피드백이 성공적으로 추가되었습니다.',
	'USER_WARNING_ADDED'			=> '사용자가 성공적으로 경고했습니다.',

	'VIEW_DETAILS'			=> '세부 정보보기',
	'VIEW_PM'				=> '비공개 메시지 보기',
	'VIEW_POST'				=> '게시물 보기',

	'WARNED_USERS'			=> '경고를 받은 사용자',
	'WARNED_USERS_EXPLAIN'	=> '만료되지 않은 경고가 발생한 사용자 목록입니다.',
	'WARNING_PM_BODY'		=> '다음은 이 사이트의 관리자 또는 운영자가 귀하에게 보낸 경고입니다.[인용]%s[/인용]',
	'WARNING_PM_SUBJECT'	=> '보드 이슈 경고',
	'WARNING_POST_DEFAULT'	=> '귀하가 작성한 다음 게시물에 대한 경고입니다: %s .',
	'NO_WARNINGS'	=> '경고가 없습니다.',

	'YOU_SELECTED_TOPIC'	=> '글 번호 %d: %s을(를) 선택했습니다.',

	'report_reasons'		=> array(
		'TITLE'	=> array(
			'WAREZ'		=> '와레즈',
			'SPAM'		=> '스팸',
			'SEX'		=> '음란물',
			'OFF_TOPIC'	=> '글과 맞지않음',
			'OTHER'		=> '기타',
		),
		'DESCRIPTION' => array(
			'WAREZ'		=> '메시지에는 불법 또는 불법 복제 소프트웨어에 대한 링크가 포함되어 있습니다.',
			'SPAM'		=> '보고된 메시지는 웹사이트나 다른 제품을 광고하는 유일한 목적입니다.',
			'SEX'		=> '음란물 성인 광고 등등',
			'OFF_TOPIC'	=> '보고된 메시지는 글에서 벗어났습니다.',
			'OTHER'		=> '보고된 메시지는 다른 범주에 속하지 않습니다. 추가 정보 필드를 사용하십시오.',
		),
	),
));
